### ISSUE TITLE
Save/Load Slidenote Gesamtkonzept

### ISSUE THREAD

**Issue by gaenseklein** [gaenseklein/slidenotes#11]
Ein Überblick wie Slidenotes speichern sollte:
Für die Aufgaben des Speicherns und Ladens wird ein neues Objekt erstellt, der slidenoteguardian. 
Der Slidenoteguardian hat folgende Aufgaben:

1. Speichern der Slidenote im CMS und localStorage
2. Laden der Slidenote aus dem CMS und localStorage
3. Speichern der Konfigurationseinstellungen im CMS und localStorage
4. Laden der Konfigurationseinstellungen im CMS und logalStorage
5. Verschlüsselung der Slidenote vor dem Abspeichern
6. Entschlüsseln der Slidenote nach dem Laden

Der localStorage hat je nach Browser zwischen 5 und 10 MB, das sollte für eine slidenote inklusive Grafiken ausreichend sein. Der localStorage ist jedoch an die Domain gekoppelt - sprich: die 5MB sind Max insgesamt für unsere App und nicht per slidenote. 
Das ist an sich auch kein Problem, da die Daten ja eh im CMS gespeichert werden sollten. Der localStorage kann jedoch wunderbar benutzt werden um Zwischenschritte zu speichern und so Last vom Server nehmen (bspw. automatische Sicherung alle 2 Minuten lokal, CMS alle 10 Minuten) 

Bilder sollten extern gespeichert werden und nicht in der Slidenote. Denn die Slidenote ändert sich öfter als die Bilder (die bleiben fast immer gleich) und verbrauchen viel mehr Speicher. Also sollten die Bilder getrennt von der Note gespeichert werden. Da sie auch im Base64-String Format sind können sie in einer Textarea bzw. im localStorage gespeichert und verschlüsselt werden. 

Um unnötiges Speichern zu vermeiden können entweder Hashes vom Originaltext bzw. Bild oder Timestamps benutzt werden. Damit kann gesehen werden, ob erneut gespeichert werden muss oder bereits der richtige Inhalt dort liegt. Näheres dazu in einer eigenen Issue.

**Comment by gaenseklein** [comment]
In diesem Thread geht es eher um allgemeine Sachen und die Entscheidungen dazu. Wie und mit welchem CMS diese später umgesetzt werden sollte in einer anderen Issue geklärt werden.

**Comment by gaenseklein** [comment]
@Jochmann 
# Vorschlag 1 
## Orientierung am normalen Editor mit Neu/Speichern/Speichern unter/Laden
Jede Slidenote wird während des Bearbeitens automatisch gespeichert im localStorage. Im localStorage wird immer nur eine Slidenote gleichzeitig gespeichert - und zwar die letzte die bearbeitet wurde. 
Sollte der Browser abstürzen oder aus Versehen geschlossen werden kann die Slidenote erneut aufgerufen/aus dem CMS geladen werden und dem User wird vorgeschlagen, die Slidenote aus dem localStorage zu laden sofern eine im localStorage vorhanden ist. Der localStorage dient damit als Puffer. 
Klickt ein User auf "Speichern" wird die Slidenote im CMS gespeichert. Im CMS werden sog. Revisionen angelegt bei jedem Speicherprozess, so das versehentlich gespeicherte Änderungen rückgängig gemacht werden können. "Automatisches Speichern" kann zusätzlich aktiviert werden, dann wird alle halbe Stunde die Slidenote automatisch gespeichert (falls sie sich geändert hat in der letzten halben Stunde). 
Klickt ein User auf "Speichern unter" wird der User nach einem neuen Titel gefragt, die Slidenote als Kopie unter diesem Titel gespeichert und geladen - ein weiteres Bearbeiten der Slidenote wird in der neuen Kopie gespeichert. 
Klickt ein User auf "Laden" wird ihm eine Liste mit seinen im CMS gespeicherten Slidenotes angezeigt und ein Klicken auf den Titel einer Slidenote öffnet selbige. 
Klickt ein User auf "Neu" wird er nach dem Titel der neuen Slidenote gefragt und selbige wird leer abgespeichert und dann geladen. 

# Vorschlag 2
## Orientierung an neueren Computerspielen - nur noch automatisches Speichern
Der User kriegt nur noch "Neu" und "Laden" als Optionen. Speichern geschieht automatisch im Hintergrund in den localStorage und nach Zeitintervallen ins CMS, sowie zusätzlich ins CMS beim/vorm "Verlassen" der Slidenote durch bspw. Neu, Laden, Abmelden und ähnliches. 

# Vorschlag 3
## localStorage als primären Speicher verwenden
Anstelle den localStorage nur als Puffer zu verwenden wird er zum primären Speicher gemacht, d.h. mehrere Revisionen vorgehalten sowie auch Slidenotes. Die Slidenotes werden im localStorage durch ihren Titel getrennt gespeichert. Großer Nachteil hierbei ist allerdings, dass nur begrenzt Platz im localStorage ist - lediglich der Opera-Browser bietet unbegrenzt Speicher für localStorage mit Zustimmung des Nutzers an. Für alle anderen gilt: 5-10MB maximum. Für alle Slidenotes. Eventuell durch geschicktes Speichermanagement sind somit 3 Slidenotes mit jeweils 3-4 Revisionen möglich. Erst ein Klick auf "In Cloud speichern" würde hier das Speichern im CMS auslösen.

**Comment by jochmann** [comment]
Automatisches Speichern (Vorschlag 2) klar bevorzugt. Entspricht Nutzer-Erwartungen aus Spielen und auch neueren Office-Paketen und Mac.

„Speichern Unter” bzw „Fork” als Option damit vereinbar? (für nicht-Programmierer erklärungsbedürftig und erst mal auch intern abzuklären: könnten wir Versionskontrolle leisten?)

Datensicherheit muss gewährleistet sein. Redundanz (über local storage hinaus) würde ich dementsprechend klar bevorzugen. Local storage ist die Basis (auch, damit offline gearbeitet werden kann) aber es muss möglichst regelmäßig ein Update in die Cloud erfolgen und auch gewarnt werden, wenn das Dokument nicht online aktualisiert werden kann. (Falls du es Sinnvoll hälst, dass Power-User die Speicherung ausschalten können, erklär mir gerne warum und wir bauen eine Option ins Menü. Default aber auf jeden Fall mit Priorität Datensicherung)

**Comment by gaenseklein** [comment]
@jochmann 
Vorschlag 2 hat zwar auch technische Schwierigkeiten (Redundanz bzw. Gewährleistung, dass immer die letzte Version im CMS abgespeichert ist), aber um die geht es hier explizit nicht. Technische Schwierigkeiten sollten in extra Issue geklärt werden. Wichtig zu klären ist, wie das Speicherkonzept aussehen soll. 
Bei Vorschlag 2 wird es natürlich kein "Speichern Unter" geben, denn das geht von einem anderen Konzept aus - nämlich eben das Speichern durch den User. Was es aber gibt (und technisch ist das quasi das gleiche) ist, eine Slidenote zu kopieren (vergleiche "Spielstand kopieren" in Computerspielen). So können sich User auch ihre eigenen Vorlagen erstellen, welche dann nur noch "kopiert" werden und danach bearbeitet werden. Wie gesagt, es geht mir hier erstmal darum, wie die Logik sein soll und dann setze ich das um. Technisch ist das zwar fast das gleiche, aber eben doch nicht ganz und daraus entwickeln sich unterschiedliche Ansätze des Programmierens bzw. Aufbaus der Speicherstruktur. 
Ein richtiges Forken wiederum, also mit Versionskontrolle, Branches etc., sehe ich weder als Zielführend noch als sinnvoll oder für die User praktikabel an.

**Comment by gaenseklein** [comment]
# Vergleich Vorschlag 1 und 2 Datensicherheit
Die Ansätze unterscheiden sich vor allem dahingehend, dass der User bei Vorschlag 1 ein größeres Gefühl der Kontrolle hat. Auch bei Vorschlag 1 wird ja genauso im Hintergrund gespeichert, aber eben nur nach bestimmten Zeitintervallen. Hier weiß der User, dass er selbst abspeichern sollte im Zweifelsfall und löst dies durch "Speichern" aus. Eine Sicherheitskopie liegt im localStorage, falls er das mal vergessen sollte und aus Versehen den Browser oder das Tab schließt oder einfach die Seite verlässt. 
Beim Vorschlag 2 muss sich der User auf das System verlassen, dass immer alles gespeichert wird. Das heißt auch, dass Fehler dahingehend nicht tollerierbar sind - der User ist nicht mehr "selbst Schuld" wenn das Programm nicht rechtzeitig gespeichert hat. Wie und ob das technisch lösbar ist soll hier aber vorerst keine Rolle spielen. Aber es ist natürlich insofern schwieriger, als dass Fehler unverzeilich sind. Mindestens eine Warnmeldung vor dem Verlassen der Seite falls noch nicht gespeichert ist sollte es geben. Gerne auch eine allgemeine Rückmeldung wenn bspw. in die Cloud gespeichert wurde. Und daher würde ich persönlich als User glaube ich den klassischen Ansatz bevorzugen, aber wenn der zweite gut klappt - warum nicht.
Ich will nur gerne wissen, welchen Ansatz ich verfolgen soll, da der zweite Ansatz durch viele Sachen schon anspruchsvoller ist - der erste ist ja relativ leicht umzusetzen. Beim zweiten Ansatz aber muss viel stärker berücksichtigt werden, wie der User agieren kann und im Zweifel viel öfter abgespeichert werden. 
Beim ersten Ansatz wäre das automatische Speichern so, dass bspw. immer in den localStorage gespeichert wird, wenn der User aufgehört hat zu tippen. (Die Abfrage gibts ja jetzt schon) Und nach Zeitintervall bspw. 10 Minuten wird geguckt, ob sich der Text verändert hat zur Version die im CMS abgespeichert ist und falls ja wird dorthin gespeichert. 
Beim zweiten Ansatz würde localStorage genauso bedient, aber die Speicherung ins CMS müsste anders geregelt sein. Es muss sichergestellt sein, dass die Daten immer vorhanden sind. Das heißt wenn bspw. eine Slidenote A geladen wird oder eine neue Slidenote aufgemacht wird muss gecheckt werden, ob die Version im localStorage - bspw. Slidenote B - bereits gespeichert ist und wenn nicht muss sie gespeichert werden bevor der localStorage überschrieben wird. Das heißt während der User Slidenote A auf hat speichert er im Hintergrund Slidenote B.

**Comment by jochmann** [comment]
der zweite Ansatz (automatisches Speichern) ist mittlerweile aber etablierte Normalität und entspricht den Erwartungen. Warnmeldung (und zusätzliche Cloud-Speicher-Trigger) beim Verlassen der Seite oder bei mangelnder Internet-Anbindung können wir ja über Abgleich mit letztem automatischen Intervall realisieren?

Duplikatskonflikte müssen wir halt ausschließen, es dürfen keine zwei Sessions gleichzeitig auf die gleiche Datei zugreifen. Die Online-Datei ist das Backup, local storage „the truth” für Synchronisation würde ich denken.

**Comment by gaenseklein** [comment]
hier passiert nix mehr. entscheidung ist längst getroffen und umgesetzt. schließe daher das issue
