### ISSUE TITLE
MD-Code-Editor splitten

### ISSUE THREAD

**Issue by gaenseklein** [gaenseklein/slidenotes#13]
Aus dem MD-Code-Editor zwei Ansätze ausarbeiten:
1.) Ersetzung der vordergründigen durch Hintergrund - also unsichtbare Schrift im Vordergrund ist über Hintergrund. Dazu muss der Prozess krass beschleunigt werden (onmousedown muss das Event bereits feuern) um Tippgefühl beizubehalten.
2.) Hintergrund als Erweiterung des Vordergrundes (jetziger Ansatz) - Textareas Schrift bleibt sichtbar um Tippgefühl etc. nicht zu beeinflussen, Hintergrund ergänzt und erweitert die Darstellung um Nuancen um den Code besser lesbar zu machen

**Comment by gaenseklein** [comment]
@jochmann Erster Ansatz ist bereits live zum Testen. 
Der Prozess ist stark beschleunigt, aber im Testverfahren. Ich verwende den gleichen Trick wie beim WYSIWYM-Ansatz zum beschleunigen, indem ich Parsen möglichst vermeide und einfachen Text einfach einfüge ohne zu parsen. Ich versuche noch herauszufinden, wann alles geparsed werden muss und versuche, das Parsen weitgehend zu vermeiden. Der Ansatz ist sau schnell wie du hoffentlich siehst - kann aber zu Fehlern in der Darstellung führen. Diese können (bereits getestet) eingedämmt werden, wenn nach untätigkeit bspw. 2 sekunden neu geparsed wird, aber eleganter wäre das Abfangen möglichst aller Notwendigen Auslösungen.

**Comment by gaenseklein** [comment]
Der erste Ansatz funktioniert so gut, dass der zweite Ansatz nicht gebraucht wird. Daher issue closed.

**Comment by jochmann** [comment]
stark
