### ISSUE TITLE
Footnotes

### ISSUE THREAD

**Issue by gaenseklein** [gaenseklein/slidenotes#22]
@jochmann Fußnoten zum Parser hinzufügen. Problem: es gibt keine allgemeine Syntax dazu. In der originalen Markdown-Syntax von Daring Fireball gibt es sie nicht. 
Bisher hatten wir uns an Githubs Markdown Codesyntax gehalten, in welchen es ebenfalls keine Fußnoten gibt. 
Typora.io definiert sie so:
You can create footnotes like this[^footnote].

[^footnote]: Here is the *text* of the **footnote**.
Das war auch der Footnote-style den wir besprochen hatten.

Definition um über das selbe zu sprechen:
Footnote-Anchor bzw. Fußnoten-Anker: Im Fließtext vorhandener Anker zur Fußnote - bspw.¹
Footnote: Unten am Ende der Seite stehende Fußnote. 

Fragen/Definitionen zum Parser:
1. Fußnoten-Anker dürfen jegliche Form haben? (bspw. Zahlen, Buchstaben, Wörter)
2. Fußnoten müssen am Ende der Seite stehen - also das letzte Element auf der Seite sein? Oder dürfen sie mitten im Text stehen, werden aber in der Ausgabe an das Ende der Seite gepackt?

**Comment by jochmann** [comment]
1. Anker dürfen jegliche Form haben. Der Parser fügt denen aber im HTML einen Hash für die fortlaufende Numerierung an. So beheben wir Fehler der User, die ausversehen die gleiche Nummer/den gleichen Namen zwei mal vergeben.

Footnote darf im Markdown-Feld im Text stehen. 
> This an example paragraph. You can create footnotes like this[^footnote].
> 
> [^footnote]: Here is the text of the footnote. You can write it like another paragraph
> 
> And the footnote will appear at the bottom of the slide where you created it.

Vielleicht hier inspirieren lassen: https://www.sitepoint.com/accessible-footnotes-css/

**Comment by gaenseklein** [comment]
> So beheben wir Fehler der User, die ausversehen die gleiche Nummer/den gleichen Namen zwei mal vergeben.

Das halte ich für nicht sinnvoll. Fußnoten in einer Präsentation werden ja auf der selben Seite angezeigt und da muss der User selbst entscheiden, was er nimmt. Mit der Syntax` [^fußnote]` für den Anker bin ich einverstanden, `[^fußnote]:` am Anfang der Zeile ist dann für die Fußnote. Wenn wir ihm schon die Freiheit geben, selbst zu definieren wie die Fußnote ist, macht es keinen Sinn wieder zu zählen. 
Bleibt noch die Frage: Muss die Fußnote am Ende der Seite stehen, also als letztes Element? 
Also ein 
```
---
Blablub [^1] blablub

[^1]: Fußnotentext Fußnote
---
```
ist in Ordnung, aber ein
 ```

---
Blablub [^1] blablub

[^1]: Fußnotentext Fußnote
Blablubtext, Image, Titel oder egal welches weitere Element
---
```
spuckt einen Parserfehler aus

**Comment by gaenseklein** [comment]
Ein 
```
---
Blablub [^1]
---
```
spuckt ebenfalls einen Fehler aus (fehlende Fußnote)
und auch ein 
```
---
Blablub
[^1]:Fußnote
---
```
spuckt einen Fehler aus (fehlender Anker)

**Comment by jochmann** [comment]
> Bleibt noch die Frage: Muss die Fußnote am Ende der Seite stehen, also als letztes Element?
> Also ein
> 
> ---
> Blablub [^1] blablub
> 
> [^1]: Fußnotentext Fußnote
> ---
> ist in Ordnung, aber ein
> 
> 
> ---
> Blablub [^1] blablub
> 
> [^1]: Fußnotentext Fußnote
> Blablubtext, Image, Titel oder egal welches weitere Element
> ---
> spuckt einen Parserfehler aus
> 
> 

Ja. Wir wollen die Leute dazu bringen, Informationshierarchie in ihren Notizen zu pflegen. Also am Ende zu schreiben, was ans Ende gehört. Das erlaubt uns außerdem später die Option, Side-Notes (Randnotizen) als zusätzliche Kategorie einzuführen (wenn ich dafür eine sinnvolle Gestaltung finde)

**Comment by gaenseklein** [comment]
Sidenotes/Randnotizen würden imho vor allem Sinn machen, wenn die Präsentation fertig ist - also dass Empfänger einer Präsentation dazu Notizen machen können um sie zurück zu schicken. Dann kannst du dir das PDF sparen - das ist der Hauptgrund, warum die Leute Präsentationen als PDF verschicken (zumindest laut Aussage eines Kollegen von Linda der im Frauenhofer arbeitet).
Fußnoten sind jetzt reingepackt. Fehlt nur noch die Ummantelung der Fußnoten am Ende der Seite mit einem `<footer>`-Tag, falls das überhaupt Not tut. (könnte per css auch anders gelöst werden) - momentan ist jede Fußnote einzeln mit einem `<footnote>`-Tag ummantelt. 
Die Fußnotenanker sind mit dem `<sup>`-Tag ummantelt.

**Comment by jochmann** [comment]
footer tag wäre gut für semantik.
footnote-tag ist selbst erfunden? da würde ich mal nach microformats-vorlagen im HTML-Standard schauen, das konform zu machen, damit es barrierefrei bleibt.

**Comment by gaenseklein** [comment]
ok, also füge ich den footer-tag noch ein. wir brauchen da auch nicht unbedingt footnote-tags, die hab ich selbst erfunden, ja. es müsste eigentlich auch ein p-tag reichen, wenn die fußnoten in einem footer-tag sind. 
laut https://www.w3.org/MarkUp/html3/footnotes.html sollten wir anstelle footnote einen fn-tag benutzen, aber ob das richtiger standard ist weiß ich auch nicht

**Comment by gaenseklein** [comment]
andere packen das in eine liste, meist ol damit es nummeriert ist aber das macht imho keinen sinn. auch eine ul macht nur bedingt sinn. den fn-tag sollte man wohl noch um einen p-tag ergänzen - was es ein wenig overkill macht imho. dann doch lieber nur p-tags in einem footer.

**Comment by gaenseklein** [comment]
fn-tag ist deprecated in html5

**Comment by gaenseklein** [comment]
footnotes sind jetzt mit p-tag ummantelt, alle footnotes einer seite sind ummantelt mit einem footer-tag

**Comment by gaenseklein** [comment]
ich schließe das issue, da alles erledigt ist. ergebnis wie immer unter dev.slidenotes.io wenn du es dir anschauen willst
