### ISSUE TITLE
Verschachtelte Aufzählungen/Listen

### ISSUE THREAD

**Issue by gaenseklein** [gaenseklein/slidenotes#24]
Der bisherige Ansatz für verschachtelte Aufzählungen/Listen funktioniert nicht. 
Githubs Markdown-Syntax - welche wir für diesen Fall auch anwenden - sieht vor, dass verschachtelte Listen mit Leerzeichen eingerückt werden. 
@jochmann: wieviele Verschachtelungen wollen wir anbieten? Github bietet nur einfache Verschachtelung an, d.h. es geht nur bis zu einer Ebene rein, keine weitere Verschachtelung/Unterpunkte. 
Also 1.1. und 1.2. ist möglich aber nicht 1.1.1., 1.1.2. 
Ich persönlich denke, einfache Verschachtelung sollte reichen für Präsentationen da alles weitere eh schwierig wird darzustellen und eine tiefer gehende Unterteilung in einer Präsentation totaler Overkill ist. 
Würde das aber gerne vorher wissen, da ich daran meine Parserprogrammierung ausrichte.

**Comment by jochmann** [comment]
nur einfache Verschachtelung.

**Comment by gaenseklein** [comment]
@jochmann hab die logik komplett umstellen müssen, da die aufteilung ordered/unordered-lists nur zu problemen geführt hat. jetzt ists in einer logik, dass nach einer liste geguckt wird und wenn eine gefunden wird dann wird halt weiter gemacht. 
die verschachtelungslogik ist dabei quasi rekursiv und einrückungen sind nach lust und laune möglich, solange sie gleich bleiben. unterscheiden sich die einrückungen werden sie als neue verschachtelung interpretiert. es sind unendlich viele unterpunkte möglich. 
der vorteil der unendlich vielen verschachtelungen ist der, dass die user nicht so viel falsch machen können und der parser nicht sonderfälle abrufen müssen. außerdem: wer mehr verschachtelung will hat sie jetzt halt.  
weiterer vorteil: spaces und tabs können benutzt werden um durch einrückungen untergliederungen zu machen bei sonst gleichbleibender syntax. 
najoa, ist krasser geworden als ich dachte und hat ordentlich hirnschmalz gekostet, aber jetzt funktionierts. 
hochgeladen ists noch nicht, nur bei mir zuhause bisher.
es ist noch ein fehler drinne, den ich grad noch nicht blicke - es werden zu viele li-end-tags gesetzt. das ist für html aber eigentlich egal :)
*korrektur:* der fehler sind nicht zu viele li-end-tags wie es scheint, sondern die sortierung der vielen li- und ul-end-tags bereitet schwierigkeiten. momentan kommt bspw. bei dreifacher kursierung - also unterpunkt vom unterpunkt vom punkt (1.1.1 bspw. oder 1.2.1.)  heraus: `</li></li><li></ul></ul></ul>` 
herauskommen sollte aber: `</li></ul></li></ul></li></ul>`. 
wär trotzdem gut, das weg zu kriegen. aber das krieg ich heut nicht mehr hin. n anderes mal.

**Comment by gaenseklein** [comment]
ok, mit nem dirty-hack hab ichs doch noch weg gekriegt. ich nehme mir zu hilfe, dass die tags alle gleich sind und positioniere sie "falsch herum". d.h. so: ul1-li1-ul2-li2-/li1-/ul1-/li2-/ul2 - eigentlich müsste es ul1-li1-ul2-li2-/li2/ul2-/li1-/ul1 sein. da aber die tags keine nummerierungen haben und auch keine klassen ist das natürlich valides html.

**Comment by gaenseklein** [comment]
Einfache Listen können jetzt erstellt werden mit 
```
* text
- text
+ text
```
Nummerierte Listen können jetzt erstellt werden mit:
```
1. text (numerische zahl - dann punkt - dann leerzeichen - dann text für listenpunkt)
1.) text (numerische zahl - dann punkt - dann klammer zu - dann leerzeichen - dann text für listenpunkt)
1) text (numerische zahl - dann klammer zu - dann leerzeichen - dann text für listenpunkt
a) text (buchstabe - dann klammer zu - dann leerzeichen - dann text für listenpunkt)
I) text (römische Zahl - dann klammer zu - dann leerzeichen - dann text für listenpunkt)
```
Alle Eingaben sind möglich mit Leerzeichen/Tabs davor. Unterschiede in den Leerzeichen/Tabs führen zu einer "neuen Einrückung" - also werden sie als neue Liste interpretiert. 

Listen werden abgeschlossen mit einer Nicht-Listen-Linie - bspw. eine Leerzeile oder Textzeile oder Titel oder Pagebreak...

Folgt eine neue Liste auf eine Liste (ohne Unterbrechung dazwischen) dann wird diese als Liste in Liste interpretiert und es tritt eine Verschachtelung auf. Beispiel:

```
1. Oberpunkt 1
a) 1. Unterpunkt zu Oberpunkt 1
b) 2. Unterpunkt zu Oberpunkt 1
2. Oberpunkt 2
a) 1. Unterpunkt zu Oberpunkt 2
b) 2. Unterpunkt zu Oberpunkt 2
3. Oberpunkt 3
  1. Unterpunkt zu Oberpunkt 3
  2. Unterpunkt zu Oberpunkt 3
```
Ordered und unordered Lists können gemischt werden. Beispiel
```
1. Oberpunkt 1
- Unterpunkt zu Oberpunkt 1
- Weiterer Unterpunkt zu Oberpunkt 1
2. Oberpunkt 2
* Unterpunkt zu Oberpunkt 2
* Weiterer Unterpunkt zu Oberpunkt 2
```
Verschachtelungen sind unendlich und hängen von der Usereingabe ab. Beispiel
```
1. Oberpunkt 1
a) Unterpunkt zu Oberpunkt 1
* Unterpunkt zu Unterpunkt a) zu Oberpunkt 1
b) Unterpunkt zu Oberpunkt 1
* Unterpunkt zu Unterpunkt b) zu Oberpunkt 1
2. Oberpunkt 2
  1. Unterpunkt zu Oberpunkt 2
     1. Unterpunkt zu 1. Unterpunkt zu Oberpunkt 2
       1. Unterpunkt zu 1. Unterpunkt zu 1. Unterpunkt zu Oberpunkt 2
```

Wird eine Liste mit einer numerischen Zahl begonnen, die nicht 1 ist, beginnt die ol mit start dieser numerischen Zahl. 
Beispiel:

```
3. Listpunkt 1
4. Listpunkt 2
5. Listpunkt 3
```
wird zu
```
<ol start=3>
<li>Listpunkt 1</li>
<li>Listpunkt 2</li>
<li>Listpunkt 3</li>
</ol>
```
Dabei ist nur die erste numerische Zahl entscheidend, der Rest wird ignoriert. 
Beispiel: 
```
3. Listpunkt 1
2. Listpunkt 2
100. Listpunkt 3
```
Führt zu selbigem HTML-Ergebnis wie das Beispiel davor.

**Comment by gaenseklein** [comment]
@jochmann ich würd das issue schließen, da es imho abgeschlossen ist. Oder hast du noch Einwände?

**Comment by jochmann** [comment]
voll gut. Dass die Beschränkung weg ist, finde ich auch OK. Bleibt die inhaltliche Verantwortung bei den usern.

**Comment by gaenseklein** [comment]
@jochmann ok, dann schließe ich dieses Issue jetzt. Nur zur Info/Belustigung: das ist die regex, mit der alle Listenmöglichkeiten gefunden werden: `/^(\s*)([\+\-\*]|(\s*)([0-9]+(\.|\)|\.\))|([a-z]|[IVX]+)\)))\s/`
Viel Spaß beim Verstehen ;) (Thats why i dont like Regex)
