### ISSUE TITLE
"_" im Markdown-Spec is parsed like "*"

### ISSUE THREAD

**Issue by jochmann** [gaenseklein/slidenotes#29]
Ich möchte ohne *character-escape* 

> Wort_Nebenwort 1, Wort_Nebenwort 2

schreiben können

**Comment by gaenseklein** [comment]
Wir kommen in Teufels Küche wenn wir anfangen, die Syntax Kontextabhängig zu machen. Aber wenn du unbedingt willst, dann würde ich die Syntax dahingehend erweitern, dass wir anstelle eines einfachen "`_`" in Zukunft ein " \_" brauchen und zum Schließen ein "\_ ". 
Bist du dir denn sicher, dass du das willst? Was kommt dann als nächstes? `*` auch genauso? Was ist mit "`__`"? oder den Zeichen für Code? "\`"
Und wollen wir Character-Escape eigentlich einbauen? Ist noch garnicht implementiert. Der Standard für Escape im Github-Markdown ist \\\* \\\_ \\\`  usw

**Comment by jochmann** [comment]
ich wollte das Zeichen _ einfach aus dem spec rausschmeißen. Nix mit Zeichenketten kontextabhängig interpretieren.

**Comment by gaenseklein** [comment]
Ok, also "\_" wird komplett rausgeschmissen? Kann ich mit leben. Hilft aber nur für den einen Use-Case und verärgert User, die das nutzen wollten weil von Github etc. gewohnt.

**Comment by jochmann** [comment]
können wir erst mal mit leben, denke ich. So ist das mit Markdown, da existieren mehrere specs, die für ihre jeweiligen use cases optimiert sind. Wundert mich fast, dass GitHub flavored Markdown _ nutzt

**Comment by gaenseklein** [comment]
ich würde das nicht prinzipiell rausnehmen sondern eher wählbar machen wollen - also ob du \* oder \_ verwenden willst. dann können die user selbst entscheiden, was für sie besser ist. ich denke nämlich auch, dass beides zu nutzen blödsinn ist, aber wenn du bspw. oft \* verwendest willst du es nicht ständig ausklammern. Bspw. bei gegenderter Sprache: Lehrer\*In

**Comment by jochmann** [comment]
guter Punkt. machen wir

**Comment by gaenseklein** [comment]
über plugin gelöst. Sternchen und Unterstriche sind jetzt unter globalOptions abwählbar wenn plugin "switchparseelements" aktiv ist. Kann natürlich gui-mäßig noch verbessert werden, aber das spielt hier jetzt keine Rolle. 
Ich habe jetzt nur Sternchen und Unterstriche generell abwählbar gemacht - heißt: Wenn Sternchen abgewählt ist geht auch kein Doppelsternchen usw.
Wenn das lieber einzeln abgewählt werden soll sag Bescheid, sonst schließ ich das Issue

**Comment by jochmann** [comment]
ich würde es schließen und als feature-option auf wiedervorlage legen

**Comment by gaenseklein** [comment]
naja, also wenn du das gerne hättest dann würd ich das lieber jetzt einprogrammieren und damit abschließen, als das auf halde zu legen und zu vergessen

**Comment by jochmann** [comment]
nee, ich würde spätere neu- oder weiterentwicklungen von diesem bereich als feature-request behandeln und den nur auf Nutzeranfrage hin noch mal anfassen

**Comment by gaenseklein** [comment]
ok, dann schließe ich das issue jetzt. funktioniert ja wie es ist.
