### ISSUE TITLE
Bilderupload: Minimierung der Bilder

### ISSUE THREAD

**Issue by gaenseklein** [gaenseklein/slidenotes#34]
Bei zu großen Bildern, welche im Base64-Format gespeichert werden, kann es zu starken Verzögerungen bis hin zum Browser-Freeze kommen. 
Als mögliche Schadensminimierung können folgende, sich ergänzende Ansätze gewählt werden:
- [x] : Maximierung der Bildgröße auf 1920x1080 (Full-HD)
- [ ] : Speichern der Bilder nicht mehr als Text sondern als Datei im CMS (anstelle Textarea nehmen wir dann ein File-Field)  
- [x] : Alternativ ausprobieren: Nicht mehr in Textarea verschieben, sondern per Javascript hochladen (REST) 
- [x] : Maximierung der Bildgröße durch den User per Auswahl

**Comment by gaenseklein** [comment]
Mit Maximierung der Bildgröße ist natürlich eine Maximierung durchs Programm gemeint - nicht, dass der User nicht größeren Content "hochladen" darf. Auch wenn letzteres gerne von vielen CMS gewählt wird als Lösung ist das für uns keine, da das den User in seiner Wahl einschränkt bzw. vor doofe Probleme stellt. Viele User wissen nicht, wie sie mit einfachen Programmen ihre Bilder kleiner kriegen.

**Comment by gaenseklein** [comment]
@jochmann
Wenn wir die Bilder verkleinern lassen könnten wir auch die User mitentscheiden lassen, wie groß das Bild maximal sein soll. Dadurch können sie die Performance deutlich steigern ohne das wir Raten müssen, worum es geht. Also wenn du bspw. ein Logo deiner Firma hochladen willst, welches nur im Header der Präsentation angezeigt werden soll macht es ja keinen Sinn, dass das trotzdem in 1920x1080 Pixeln abgespeichert wird, sondern eher so etwas wie 300x200 o.ä.
Mir schwebt hier eine einfache Vorauswahl vor, die der User treffen kann wie bspw. 

1. Hintergrundbild (1920x1080)
2. Logo (300x200)
3. Großes Bild (800x600)
4. Kleines Bild (640x480)
5. Selbst gewählt (Usereingabe x Usereingabe)

Bilder werden immer nur heruntergerechnet, nicht hoch. Hochrechnung passiert später im Browser durch das CSS wenn es sein muss, aber es macht keinen Sinn, das Bild vergrößert abzuspeichern, da die Qualität eh nicht besser wird. 

Alternative wäre, das Herunterrechnen automatisiert zu machen, je nachdem wo bzw. wie das Image verwendet wurde.

**Comment by gaenseklein** [comment]
Anleitungen Verkleinern von Bildern mit Hilfe von Canvas:
https://davidwalsh.name/resize-image-canvas
https://stackoverflow.com/questions/19262141/resize-image-with-javascript-canvas-smoothly
https://www.liip.ch/en/blog/resizing-images-with-javascript

**Comment by jochmann** [comment]
wir rechnen automatisch auf 1080p runter. Lass uns die Überlegung, ob wir Auswahl anbieten, auf Version 2.0 verschieben. Erst mal klein anfangen (gerade auch mit dem User Interface und Auswahloptionen)

**Comment by gaenseklein** [comment]
# Testresultate Images verkleinern
Alle Bilder werden als image/jpeg gespeichert. Die Bilder werden verkleinert, wenn sie größer als maxwidth sind.
Die Verkleinerung passiert in mehreren Schritten um Qualität zu verbessern.
Um zu testen, was wieviel so ist mal hier ein Test mit verschiedenen Größen und Qualitäten:
Im Test wird ein Bild hochgeladen, verkleinert, als base64-url umgewandelt und verschlüsselt. 
Die Verschlüsselung enthält noch ein paar Bytes an Zusatzinformationen, die sind aber zu vernachlässigen aufgrund ihrer geringen Größe. 
Kommt nicht an ein Kilobyte ran, auch nicht bei vielen Bildern. 

# maxwidth: 1024 px:
quality: 0,7 origbild: 2,9 mb buchstaben gesamt: 140429 - gespeichert: 280kb
quality: 0,8 origbild: 2,9 mb buchstaben gesamt: 180873 - gespeichert: 350kb
# maxwidth: 1920 px:
quality: 0.8 origbild: 2,9mb buchstaben gesamt: 484637 - gespeichert als datei: 970kb
quality: 0.7 origbild: 2,8mb buchstaben gesamt: 325441 - gespeichert als datei: 650kb

# Browserfreeze-Test
Bei einem Bild ohne Verkleinerung von 2,9Mb kam es zum Browserfreeze. 
## Annäherung durch Verkleinerte Bilder
Bei einem Bild, 1024 Width, kam es zu keinem fühlbaren Browserfreeze. Ab da 1920er-Bilder eingefügt.
Bei zwei Bildern, insgesamt 392534 Zeichen, kam es zu kurzzeitigem Browserfreeze (paar Sekunden).
Bei drei Bildern, insgesamt 723847 Zeichen, kam es zu kurzzeitigem Browserfreeze (paar Sekunden).
Vier Bilder, 1054020 Zeichen, Browserfreeze über 10 Sekunden
Fünf Bilder, 1605961, Browserfreeze über 15 Sekunden
Sechs Bilder, 2227258 Zeichen, Browserfreeze 20 Sekunden (wird schon nervig)
Sieben Bilder, 2616795 Zeichen, Browserfreeze ca. 30 Sekunden
Acht Bilder, 3179436 Zeichen, Browserfreeze ca. 45 Sekunden
Zehn Bilder, 3771042 Zeichen, Browserfreeze ca. 50 Sekunden
				
Maximum für localStorage sind 5200000 Zeichen im Firefox und Chrome. Das wären 10 Bilder in FullHD mit Qualität 0.8 - mit Qualität 0.7 kommen wir auf 12-13 Bilder. 
Allerdings wird es ab dem zweiten Bild zu einem Browserfreeze kommen, wenn der Text in die Textarea kopiert wird.

**Comment by jochmann** [comment]
der browserfreeze bei mehreren Bildern ist schon ein Problem.
ginge ein round-trip für die bilder via server? dass die Base64-Operation (zur Not unverschlüsselt) auf dem Server statt findet und das Ergebnis nach und nach an den Client zurück gegeben wird?
Wenn der Client zur Entlastung nur mit 720px (oder noch weniger) als Platzhalter arbeitet?

**Comment by gaenseklein** [comment]
für den browserfreeze wie er bei mir auftritt sehe ich schon noch andere möglichkeiten. (siehe möglichkeit 2 oben, ersetzen der textarea durch einen fileupload. Oder partielles Kopieren in die Textarea, die der Browser verkraften kann. Oder Aufteilung auf mehrere Textareas, welche dann jeweils maximal so viel Text bekommen, wie sie ohne Browserfreeze verkraften können.) Der freeze tritt (bei mir) auf, wenn ich den text in die textarea kopiere, nicht, wenn ich die bilder umwandel oder sonstwie bearbeite. 
ob er auch auftaucht, wenn er als source an ein bild angehängt wird wäre interessant, aber ist mir so nicht aufgefallen. 
Zu Testen wäre es, wie sich ein schwächerer Rechner bspw. ein Ipad dort verhält. 

Was ich an den Testergebnissen spannender finde ist die Tatsache, dass wir viel zu Hart an der Grenze des Möglichen arbeiten. 10 Bilder Maximum für eine Präsentation ist nicht cool. Auch die Belastung für unsere Datenbank ist nicht cool, wenn pro Präsentation ständig 10MB hochgeladen werden. 
Ich glaube, es sollte zumindest möglich sein, die Bilder kleiner zu machen. Mindestens mit Bestimmung der User (siehe oben, zusätzlich vielleicht noch: "Wähle maximale Ausgabe: FullHD, HD, SD..."), Maximal mit automatischer Bestimmung durchs Programm. (Wenn Bilder als Hintergrundbild verwendet werden maxsize fullHD. Wenn Bilder als Logo verwendet werden maxsize 10% von fullHD. Wenn Bilder als großes Bild verwendet werden maxsize 60% von fullHD usw.)  
Es ist sowohl für uns (Bandbreite und Datenbank) als auch für den Erstelleruser der Präsentation (Browserfreeze) als auch für den Empfänger der Präsentation (Bandbreite) von großem Nutzen, wenn die Bilder nicht zu groß sind. Daher würde ich damit nicht bis Version 2 warten.

**Comment by gaenseklein** [comment]
By the way: Die 10 Bilder sind bei Qualitätsstufe 80%, für hohe Qualität nimmst du eigentlich 90%. Dann sind das noch weniger Bilder: 
quality: 0.9 origbild: 2,9mb buchstaben gesamt: 743681 -> max. 6 Bilder

**Comment by gaenseklein** [comment]
Ich wäre daher dafür: Maximale Auflösung ist 1024x768. Wer Super-HD-Mega-Qualität haben will, der muss die Bilder entweder bei uns oder woanders (unverschlüsselt!) hochladen. Die Technik ist einfach nicht für die Größenordnung an Bildern gebaut.

**Comment by jochmann** [comment]
ja.
klassischer Fall von "zum Start geht es nur so" - ich würde sogar die Anzahl der Bilder willkürlich auf 10 begrenzen. Passt ja auch zum Kern-Anspruch des Produkts, dass wir die Notizen in den Mittelpunkt der Funktionalität stellen.

und wenn wir für FullHD und mehr Bilder später eigens noch nach anderer Technik suchen oder Lösungen bauen, dann wird das ein Premium-Feature, was wir gegen Bezahlung anbieten/entwickeln

**Comment by gaenseklein** [comment]
denk ich auch. fullHD unterstützung kommt evtl. später, zum start erstmal nur so. fremdeingebundene bilder können ja weiterhin fullHD sein, sind dann halt nur nicht verschlüsselt und wo sie hochgeladen sind muss sich der user selbst drum kümmern. 
Trotzdem würde ich auch jetzt schon anbieten, dass der User mitentscheidet, wie groß das Bild skaliert werden soll. Das ist kein großer Aufwand, das zu implementieren, und es ist ja kein Zwang da es zu nutzen. Wenn es aber genutzt wird hilft es sehr viel. Dem User aber auch uns.

**Comment by jochmann** [comment]
ok

**Comment by gaenseklein** [comment]
technik ist jetzt anders gelöst, nämlich mit REST, dadurch entfällt die gesamte Problematik. Issue ist damit veraltet und nicht mehr aktuell - closed
