### ISSUE TITLE
Escape-Letter für Markdown

### ISSUE THREAD

**Issue by gaenseklein** [gaenseklein/slidenotes#35]
Durch die Markdown-Syntax ist es nicht möglich, \*, \_ und \` zu schreiben. 
In der Markdown-Syntax ist dafür das Escape-Zeichen \\ vorgesehen, um diese Zeichen trotzdem schreiben zu können. 
@jochmann Wollen wir das auch bei uns einführen?

**Comment by jochmann** [comment]
Ja

___
http://jochmann.me
exploring meaning in communication

**Comment by gaenseklein** [comment]
done. \\ escaped jetzt \*, \**, \***, \_, \__, \`, \```, \![ und \~~. link ist noch nicht gemacht, aber link ist eh doof.
