### ISSUE TITLE
Editor markdown-vorschau bleibt in kursiv, obwohl tag geschlossen ist

### ISSUE THREAD

**Issue by jochmann** [gaenseklein/slidenotes#40]
auf Safari MacOS. Siehe screenshot

<img width="570" alt="screenshot 2018-09-14 13 46 03" src="https://user-images.githubusercontent.com/2007300/45548520-d6fc6a00-b824-11e8-96ef-ec57da92fe97.png">

**Comment by gaenseklein** [comment]
hmm... kann ich nicht reproduzieren im chromium. bleibt das so, wenn du enter gedrückt hast? oder backspace oder ähnliches?

**Comment by jochmann** [comment]
backspace macht keinen unterschied, nach enter normalisiert sich die Anzeige und der Teil, der nicht innerhalb der Sternchen steht, wird wieder in regulärer Schrift angezeigt

**Comment by gaenseklein** [comment]
existiert der bug immer noch? ist ja inzwischen einiges passiert. ich denke, es war ein fehler, der zurückzuführen war auf fehlendes neu parsen. so zumindest reproduziert er das bei mir: es wird kursiv dargestellt, bis das parsing greift (nach inaktivität von ca. 300ms) und dann ändert es sich richtig. würde den bug dann schließen, wenn das sich bei dir genauso verhält.

**Comment by jochmann** [comment]
Ja, verhält sich bei mir auch so: auch nach geschlossenem Tag kursiv so lange, bis keine Eingabe erfolgt. dann wird alles nach dem geschlossenen Tag wieder regulär dargestellt.

Können wir das noch irgendwie erzwingen, dass schneller oder schlauer geparst wird? Wenn jemand schnell tippt, ist das schon irritierend, wenn die Schrift während des Tippens falsch ausgezeichnet dargestellt wird.

**Comment by gaenseklein** [comment]
müsste ich gucken, ist aber ein anderes problem. Das problem tritt auf, *weil* ich versuche, das schnell und schlau zu parsen bzw. eben extra nicht zu parsen, um keine verzögerung zu haben. Ich vermute tatsächlich, dass es die Cursorposition ist, die mir hier einen Strich durch meine Rechnung macht. das heißt: bei Abschluss des Tags steht der Cursor noch in dem Tag drinne, so dass folgende getippte Buchstaben ebenfalls in den Tag reingeschrieben werden. Beim Neu parsen korrigiert sich das. Das ganze findet in dem kritischsten Bereich statt den das Programm hat, nämlich dem schnellen Tippen. Und um da keine Verzögerung aufkommen zu lassen lasse ich ja gerade extra nicht parsen. Heißt: Um das zu beheben müsste ich warscheinlich die Cursorposition neu berechnen - dazu müsste ich aber neu parsen - und das bedeutet, dass es eine Verzögerung beim Tippen gibt. Das heißt so oder so wird es zu einem warscheinlichen "Bruch" im Tippgefühl kommen. Und da fand ich die bisherige Lösung eleganter. Nach einer kleinen Tipp-Pause korrigiert sich das ja und solange es keine Tipp-Pause gibt ist es imho wichtiger, dass die Buchstaben schnell auftauchen (des Tippgefühls wegen) als dass sie *nicht kursiv, aber mit Verzögerung* auftauchen.

**Comment by gaenseklein** [comment]
ich lass den bug nochmal offen,  ich gucks mir nochmal an, ob ich vielleicht den cursor besser gesetzt kriege, so dass er bereits außerhalb des tags steht und das dann verschwindet. mit cursor meine ich, dass es im text ein tag gibt: `<span id="carret"></span>` und in dieses wird der text immer sofort reinkopiert, der neu getippt wird. dadurch ist es so schnell. erst wenn es ca. 300Ms keine Eingabe gab wird neu geparsed um eben ein "ruckeln" beim tippen zu vermeiden, da das extrem störend ist. 
momentan sieht es so aus, als ob der cursor links vom `</i>`-tag gesetzt ist und nicht rechts, wie es eigentlich sein müsste. 
daher müsste das eigentlich behebbar sein, wenn der cursor richtig gesetzt wurde. das passiert anscheinend auch nachträglich, also wenn der cursor so steht: `*kursiv-tag*| weiterer text` und losgetippt wird passiert das auch.

**Comment by gaenseklein** [comment]
war einfacher als gedacht... eine sort-funktion war falsch und hat nicht gearbeitet wie sie sollte, dadurch wurde der cursor falsch einsortiert. jetzt läufts wie gewünscht.
