### ISSUE TITLE
Bilder als Hintergrund

### ISSUE THREAD

**Issue by gaenseklein** [gaenseklein/slidenotes#42]
Um Bilder in den Hintergrund zu packen gibt es verschiedene Lösungen:
1. Das Bild wird aus der **DOM entfernt** und der *slide* (*ppage*) als *Hintergrund-style* gegeben
2. Das Bild wird mit *Position:absolute* und *z-index:-1* aus dem **Flow** der DOM **entfernt** und absolut positioniert
3. Das Bild wird über das **Grid** des slides positioniert

Welche Lösung bevorzugt wird hängt im Endeffekt mehr von den verwendeten Themes ab und sollte da entschieden werden. Damit das Theme darauf reagieren kann bekommt ein Hintergrundbild die klasse ***bgimg*** angehängt. 

In blocks.js bspw. wird das element mit klasse bgimg aus der template-Area-Berechnung herausgelassen und anschließend über das gesamte Grid gespannt. 

# Parsing des Hintergrundbildes
@jochmann Wir hatten im Gespräch vereinbart, dass das erste Element auf der Seite, so es ein Bild ist, als Hintergrundbild verwendet. Das halte ich nach weiterer Überlegung für falsch. Es sind dadurch mehrere Möglichkeiten der Interpretation vorstellbar. Nimm folgenden Code:
```
---

![](bild1)

---
```
Kann folgendes heißen:
1. Verwende bild1 als Hintergrundbild und strecke es über die verfügbare Seitengröße
2. Verwende bild1 als Seitenelement/Bild und packe es bspw. in die Mitte der Seite

Beides sind vorstellbare Wünsche des Users. Um beides zu ermöglichen und eine Eindeutigkeit hervorzurufen habe ich geändert, dass Hintergrundbilder immer **direkt** am Anfang einer Seite stehen. 
Eine Leerzeile zwischen Seitenanfang und Bild bedeutet, dass es **nicht** als Hintergrundbild verwendet wird. Beispiel:
```
---
![](bild1)

lorem ipsum usw.
---

![](bild2)

lorem ipsum usw.
---
```
bild 1 wird hier als hintergrundbild genommen und gestreckt, bild 2 dagegen als seitenelement aufgefasst. 
das ist logisch und konsistent anwendbar und auch durch try-and-error des users leicht zu erlernen bzw. zu verbessern.

**Comment by jochmann** [comment]
ich würde hier den usern die Wahl abnehmen. 
> Verwende bild1 als Seitenelement/Bild und packe es bspw. in die Mitte der Seite
eliminieren wir als Möglichkeit. Ein Bild ohne weitere Elemente auf einer Folie wird immer(!) als Hintergrundbild vollflächig angezeigt.
Was wir statt dessen (oder wenigstens zusätzlich) als Weiche einbauen sollten ist eine Prüfung, ob das Bild groß genug ist in der Auflösung, dass es vollformatig angezeigt werden kann. Dann mit Warnung beim Hochladen?

**Comment by gaenseklein** [comment]
Entweder du hast den Text nicht ganz gelesen oder nicht verstanden. 
Du gehst nur auf den ersten Sonderfall ein, der zweite ist dagegen viel häufiger. 
Ich bleibe dabei - es MUSS ohne Leerzeile geschrieben sein, weil nur so eine Eindeutigkeit gegeben ist wie das Bild zu interpretieren ist. 
Wenn du das Bild als erstes Element immer als Hintergrundbild interpretierst verbaust du dir die Möglichkeit, Bilder als **erstes Seitenelement** zu benutzen. Warum willst du das? Macht überhaupt keinen Sinn.

Dagegen sehe ich es als absolutes Selbstverschulden des Users an, wenn sein Hintergrundbild nicht groß genug ist. Eine Warnung beim Hochladen macht hier auch keinen Sinn, da du zu der Zeit noch garnicht weißt, ob es als Hintergrundbild oder als Seitenelement benutzt werden soll.

**Comment by jochmann** [comment]
ok, fair

**Comment by gaenseklein** [comment]
Bilder können jetzt als Hintergrund gesetzt werden und werden vom blocks-plugin auch interpretiert. 
Wenn das sections-plugin an ist können auch sections definiert werden mit eigenem Hintergrundbild. Damit ist es auch konsistent möglich, Bilder mit Texten zu versehen - einfach eine ||section|| einführen mit hintergrundbild:
```
||section||
![](meinbild)
Text der über das Bild geht
||section||
```
