### ISSUE TITLE
Mehrere Slidenotes im Browsercache abspeichern

### ISSUE THREAD

**Issue by gaenseklein** [gaenseklein/slidenotes#44]
Momentan ists nur möglich, eine Slidenote im Browsercache vorzuhalten. 
Das soll erweitert werden, um bereits Notizen speichern zu können. 
Dazu braucht es 

- [ ] a)  ein Konzept wie slidenotes gespeichert werden (Titel o.ä. zum Unterscheiden der Slidenotes) 
- [ ] b) eine Übersichtsseite, auf der die gespeicherten Notes ausgewählt werden können
- [ ] c) eine Abfrage, wieviel Speicher jeweils verbraucht ist und wieviel noch frei ist
- [ ] d) eine Übertragungsmöglichkeit, um im Cache gespeicherte Notes in die Cloud hochzuladen

**Comment by gaenseklein** [comment]
Theoretisch ist das kein Problem. Praktisch aber erscheint es mir nicht sinnvoll. Es würde sich mit unserem bisherigen Cloud-First Speicheransatz beißen. Wenn es Client-First Speicheransatz sein soll wäre das eine komische Mogellösung weil es nicht besser machbar ist innerhalb des Browsers. Aber auch dann hat es kaum einen Sinn, weil bei einem Client-First Ansatz die Cloud nur zum synchronisieren da sein soll. Dann hat es aber keinen Sinn, dass die User das Programm im Browser im Internet laden müssen, sondern es sollte auch beim Client laufen. Und ab da gehts halt nicht mehr easy-peasy Plattformübergreifend. Entweder für jedes OS n eigenes Programm (Electron bspw. für Desktops) oder aber n Plug-In für den Browser. Und das wollten wir ja nicht. 
Es könnte höchstens Sinn machen, wenn wir das als Test-Version so benutzen. Also als Werbung, ohne dass die User sich auf der Seite anmelden, sondern als Gratis-Version ohne Cloudunterstützung.

**Comment by gaenseklein** [comment]
@jochmann
ich schließe das issue, da es in der pdf auch nicht auftaucht. idee verworfen/nicht weiterverfolgt? 
da die praktische umsetzung mir nicht sinnvoll erscheint schließe ich es erstmal.

**Comment by jochmann** [comment]
ja, mehrere slidenotes parallel zu bearbeiten sollte nur für zahlende nutzer über den server ermöglicht werden.
