### ISSUE TITLE
Export/Import Funktion für Roh-Slidenotes bereits einführen

### ISSUE THREAD

**Issue by gaenseklein** [gaenseklein/slidenotes#45]
Exportieren und Importieren soll bereits in der ersten Version enthalten sein. 
Ein "Export" soll eine Datei erstellen, die verschlüsselten MD-Code enthält, welcher vom User gespeichert werden kann. 
Ein "Import" soll eine Datei mit verschlüsseltem MD-Code und mit unverschlüsseltem MD-Code einlesen können. 
Ein Export der Präsentation ist damit nicht gemeint. 

- [x] Import von MD-Code
- [x] Import von verschlüsselter Slidenote
- [x] Export von verschlüsselter Slidenote via saveAs() aka. FileSaver.js
- [x] Export von unverschlüsseltem reinem Code aus der Textarea als Textdatei via FileSaver.js
- [ ] Export von verschlüsselter Slidenote via serverseitigem Skript
- [ ] Export von unverschlüsseltem reinem Code aus der Textarea als Textdatei via serverseitigem Skript

**Comment by gaenseklein** [comment]
Export direkt aus Javascript scheint Probleme mit Safari zu machen. Für alle anderen könnte FileSaver.js eine einfache Lösung darstellen. Ausweichmöglichkeit für Safari wäre evtl. die Datei an den Server zu schicken und von dort aus an den User zurück werfen. Gibt zwar unnötigen Traffic, aber wäre möglich. Ist nur ärgerlich, dass so Internetverbindung gebraucht wird.

**Comment by gaenseklein** [comment]
Export ist jetzt mit FileSaver.js gelöst zum Dateispeichern. Klappt in Chromium und Firefox prima. Leider ist die Dokumentation von FileSaver.js an der Stelle ungenau. Safari 10.x soll wohl unterstützt werden, aber IOs 6.x> mache Schwierigkeiten und öffne die Datei in einem neuen Tab anstelle es zu speichern. Heißt - wir müssen prüfen, ob das neue IPad das unterstützt. Falls nicht kann das aber einfach durch ein PHP-Skript oder ähnliches gelöst werden. Siehe oben. 
@jochmann
Als Export wird eine verschlüsselte Textdatei erstellt mit der Endung .slidenote. In dieser verschlüsselten Datei enthalten ist der MD-Code der Slidenote sowie die hochgeladenen Bilder. Der Export kann mit einem anderen Passwort versehen werden. 
Import ist mit der FileReader Api (HTML5) gelöst und hat diese Schwierigkeit nicht. Zum Import ist es möglich, eine Textdatei (Endung .txt oder .csv), eine md-code-datei (Endung .md) und eine exportierte Slidenote (Endung .slidenote) zu laden. Diese wird sofort geladen in die Textarea und den Speicher falls die bisherige Textarea leer ist. Ansonsten wird die Datei in einer Voransicht dargestellt und der User kann entscheiden, ob er sie in die bestehende Slidenote einfügen will oder die bestehende Slidenote ersetzen will.

**Comment by jochmann** [comment]
cool.

gerade auf iPad getestet: bei klick auf "export markdown" (und Eingabe von Passwort) öffnet sich nach "speichern" folgende Seite im gleichen Tab (siehe screenshot)

**Comment by gaenseklein** [comment]
hast vergessen, den screenshot anzuhängen, aber wenn er die datei eben nicht speichert sondern öffnet ist das natürlich blöd und entspricht dem, was in der doku zu filesaver.js steht. Ist n bug von IOs und es ist fraglich, wann sie den beheben. 
Ist für uns aber auch nicht sonderlich schlimm. Heißt halt nur, dass es bei Ipads und Co nur mit Serverunterstützung funktioniert. Aber Ipads und Co sind ja direkte Exporte eh nicht so angesagt, da du ja aufm Pad seltener mit nem Filesystem arbeiten willst.

**Comment by gaenseklein** [comment]
Exportieren ist jetzt auch zu unverschlüsselter .md textdatei möglich.

**Comment by gaenseklein** [comment]
import ist jetzt über den schöneren Import-Button gelöst

**Comment by gaenseklein** [comment]
server-seitiges script soll wohl nicht mehr vonnöten sein im neuen safari. daher ists fertig wie es ist
