### ISSUE TITLE
Export Slidenotepresentation

### ISSUE THREAD

**Issue by gaenseklein** [gaenseklein/slidenotes#48]
Grundsätzlich wird es zwei verschiedene Wege geben eine Slidenotepräsentation zu exportieren: 
1. über slidenotes.io zugänglich machen (Cloud)
2. lokal abspeichern und bspw. per e-mail verschicken (local)

Dabei gibt es als Unterpunkte zu klären:
Cloud:
1. sollen die slidenotes öffentlich zugänglich sein? 
2. wenn nein, wie soll sich das CMS um die Zugangsregelung kümmern? 

local:
1. soll sich javascript oder das cms um das speichern der präsentation kümmern? 
2. soll immer verschlüsselt abgespeichert werden oder bieten wir auch an, ohne Verschlüsselung zu speichern um bspw. Kompatiblitätsprobleme beim Empfänger zu vermeiden? (encrypted-first aber unencrypted-optional?) 
----
stadium der diskussion: 
3 export-möglichkeiten:

- [x] 1. publish to slidenote.io (cms)
- [x] 2. save as encrypted .html
- [x] 3. save as unencrypted .html

**Comment by gaenseklein** [comment]
# Cloud:
## 1. sollen die slidenotes öffentlich zugänglich sein?
### Pro: 
1. Es kann ein Link rumgeschickt werden, es braucht keine Credentials oder weitere Passwörter. Zusätzliche Sicherheit kann gewährleistet werden, in dem die Präsentation über Invitation-Link veröffentlicht wird - d.h. es gibt eine von außen nicht erratbare eindeutige pseudozufällige URL, hinter der die Präsentation versteckt wird
2. Die Präsentation ist eh verschlüsselt - d.h. User ohne Passwort kriegen nur verschlüsselten Content geliefert
3. Empfänger der Präsentation brauchen keine Anmeldung an der Webseite oder ähnliches sondern können direkt die Präsentation sehen - vorausgesetzt, sie haben das Passwort gekriegt
4. Empfänger der Präsentation können direkt die Präsentation kommentieren ohne selbst an der Plattform angemeldet zu sein. Dank Verschlüsselung über Passwort kann Spam ausgefiltert werden - nur verschlüsselte Kommentare werden zugelassen

### Contra:
1. Die Verschlüsselung ist das einzige wirkliche Sicherheitslayer. Da die Verschlüsselung über Passwort passiert ist es zudem eine äußerst schwache Verschlüsselung (je nach Wahl des Passworts Sicherheitsstufe unsicher bis sehr sicher alles dabei) 
2. Die Spamabwehr muss funktionieren ohne das wir selbst moderieren. Funktioniert sie nicht wird es die Kommentarfunktion ad absurdum führen weil sie zugespammt wird (wird evtl. durch pseudozufällige URL auch weitgehend minimiert wenn Robots die URL nicht herausfinden) 

## 2. Soll sich das CMS um die Zugangsregelung kümmern? 
Wenn das CMS sich um die Zugangsregelung kümmern soll bleiben mehrere Optionen offen, wie dies geschehen soll. 
Möglichkeiten wären: 
1. Zugangsdaten: Empfänger müssen im CMS angemeldet sein - bspw. über Gast-Accounts die mit dem Sender-Account verknüpft sind (bspw.: Sender kann Gast-Account erstellen) 
2. Invitation-Link: Empfänger bekommt eine pseudozufällige URL zur Präsentation geschickt, welche nur begrenzt haltbar ist - bspw. eine Woche oder auswählbar durch den User

Hier gibts viele Pros und Contras abzuwägen. Eigene Zugangsdaten für die Empfänger (bspw. Gast-Accounts vom Sender) erhöhen die Sicherheit, aber auch die Komplexität: Der Empfänger muss nicht nur das Passwort der Präsentation sondern auch die Zugangsdaten (account-name + passwort) bekommen um die Präsentation sehen zu können. Heißt es wird umständlicher für ihn bis er die Präsentation zu sehen bekommt und die Komplexität verleitet User dazu, das selbe Passwort für die Präsentation wie für den Gast-Account zu nehmen. Dann aber wird das Passwort als Hash in der Datenbank gespeichert, was die Sicherheit der Präsentation gegenüber 0-Day-Attacken deutlich schmälert.  
Ich tendiere momentan wegen der Usability dazu, die Slidenotes semi-öffentlich - also per Invitation-Link - zu machen. Fraglich ist, wie lange der Invitation-Link gültig sein sollte. 

# local:
## 1. soll sich javascript oder das cms um das Speichern der Präsentation kümmern?
Wenn Javascript sich um das Speichern kümmert bedeutet das zum einen weniger Load für den Server, größere Sicherheit für den User da sein Content nicht erneut zu unserer Seite gespiegelt wird (Paranoiker könnten die Cloud-Lösung komplett ignorieren? Als Feature anbieten?) und es machts einfach, auch unverschlüsselt Präsentationen abzuspeichern ohne das unser Server mit dieser in Kontakt kommt. 
Nachteil ist klar, dass es für uns keine Überprüfungsmöglichkeit mehr gibt, wie oft der User seine Präsentation exportiert und ob überhaupt. Eine Monetarisierung pro Präsentation scheidet damit ebenfalls aus falls das doch erwünscht ist. Eine Mischlösung wäre, wenn das Speichern selbst zwar per Javascript ausgelöst wird, der Aufbau der Seite/des Templates allerdings per PHP generiert, ans Javascript zurück gemeldet und dann von diesem verwendet wird um die Präsentation zu exportieren. Bspw. der css-block ohne den die Präsentation nach nix aussieht. 

## 2. Soll immer verschlüsselt abgespeichert werden oder bieten wir auch optional an, ohne Verschlüsselung zu speichern? 
Da die Verschlüsselung auf webcrypt aufbaut und dadurch nur moderne, up-to-date Browser (Stand 2017) unterstützt werden kann es hilfreich für User sein, wenn sie die Präsentation auch ohne Verschlüsselung speichern können - damit sie bspw. von einem Empfänger, der nur Internetexplorer hat oder ähnliches ebenfalls angesehen werden kann. Wenn wir das anbieten sollten muss sich aber imho Javascript um die Speicherung kümmern, ansonsten bouncen wir die unverschlüsselte Präsentation zu unserem Server und wieder zurück. Auch wenn dies über https geschieht und wir die Kontrolle über das CMS behalten - ergo nicht in die Datenbank speichern müssen oder ähnliches - ist das ein Ansatzpunkt, der es angreifbar machen könnte (0-Day-Attacke) und bei Usern ein "Unsicherheitsgefühl" hervorrufen könnte. Präsentationen, die mit I-Pad erstellt werden, hätten diese Möglichkeit daher nicht, da sie auf eine Serverseitige Erstellung angewiesen sind - also mindestens die Präsentation einmal unverschlüsselt zum Server hingeschickt und wieder zurück bekommen wird.

**Comment by gaenseklein** [comment]
@jochmann lies dir das bitte mal durch. in der pdf hab ich das gefühl, dass du die cloud überhaupt nicht auf dem schirm hast. siehe deine export-strategien. allerdings hab ich mir inzwischen weitere gedanken gemacht, die da noch nicht eingeflossen sind. trotzdem: cloud-first war unser ansatz und das sollte es auch bleiben. dann haben auch ipad user was von slidenotes.io ;)

**Comment by jochmann** [comment]
# cloud
## öffentlich zugänglich

ja, am liebsten mit transparenten URLs. Wir vertrauen darauf, dass Passwort als Spam-Filter dient. grundsätzlich sind Backups ein gutes Fallback und bei uns mit reinen Textdateien ja auch super elegant und einfach. Hier ist Nutzer-Verantwortung gefragt (wie auch bei der Wahl des Passwortes). Wir fördern die Prominenz von Backups indem wir
1. Import von Textdateien im user interface immer wieder als relevant anbieten
2. Export von Textdateien im UI immer wieder anbieten

in der Cloud und per E-Mail-Versand werden nur verschlüsselte Dateien angeboten. Die müssen dann in slidenotes.io zum Öffnen importiert werden. Unverschlüsselter Export für Lokal kann über das Bereitstellen in einem Textfeld passieren, aus dem du manuell rauskopieren kannst. Das sollte also auch auf dem iPad funktionieren. Eigentlich kommen ja nur die hochgeladenen Bilder als Text hinzu, weil der Rest ja ohnehin aus dem Textfeld schon rauskopiert werden kann.

## cms

brauchen wir hauptsächlich für die Verwaltung mehrerer Files. Eigentlich könnten die User das selbst lokal in ihrer persönlichen Ordnerstruktur vorhalten und zum anonymen Bearbeiten jeweils neu importieren. Wir bieten quasi nur die bequeme Option, alle slidenotes auf einen Blick online verwaltet zu sehen. 

Außerdem können wir unserem JavaScript per API sagen, ob ein angemeldeter (zahlender) Nutzer gerade ein Dokument bearbeitet oder jemand anonym arbeitet, und für angemeldete Nutzer Optionen freischalten (wie Export zu PDF oder mehr Themes)

# local

## javascript oder cms

JavaScript kümmert sich um den Export. Ich glaube, dass wir trotzdem einzelne Features beim Export und beim Erstellen monetarisieren können. Z.B. Freischalten durch API oder Round-Tripping zum Server für css-injection, wie du das beschrieben hattest.

überprüfen, ob exportiert ist, müssen wir nicht - könnten wir aber auch als Warnung oder Erinnerung abfragen (und die Warnung zur Option machen, die man ausstellen kann).

## Verschlüsselung

ich würde sagen, dass unser Server nur verschlüsselte Dateien sieht, aber du die Option für unverschlüsselte Export-Dateien bekommst. Bis zum Export also alles immer verschlüsseln.

Für die reine Anzeige von Präsentationen online sollten wir dann vielleicht auch ein "Publish to slidenotes/public" für angemeldete User erlauben? Hier würden wir nur unverschlüsselte HTML-Dateien, optional hinter einer eigenen Passwortabfrage vorhalten. Die Verantwortung liegt wieder bei den Nutzern, ob sie die Daten unverschlüsselt auf unserem Server liegen haben möchten.

Oder wir beschließen, dass wir ohnehin auch für die Anzeige der Präsentationen alle Browser ausschließen, die älter als 2017 sind. Was ich eigentlich stark befürworten würde. Scheiß auf IE, unser Publikum sind Nerds, nicht Bürohengste mit veralteter IT-Struktur.

ich dachte, dem iPad fehlt nur die Option, den Export im gleichen Fenster anzuzeigen?
Fehlt etwa die webcrypt-Verschlüsselungs-API??

**Comment by gaenseklein** [comment]
vorschlag: überlass die cloud und export mir. ich hab mir da viel mehr gedanken zu gemacht als du und bin da viel weiter. kümmer dich um andere baustellen und gib mir input, wenn dir was nicht gefällt. aber so macht das für mich keinen sinn - ich hab ein ausgefeiltes konzept im kopf und versuch es aufzuschreiben und du antwortest noch am selben tag darauf mit einem unausgegorenem, nicht schlüssigen konzept. 
wir haben so viele baustellen, dass ich es gut finden würde, wenn du dir über all die anderen sachen gedanken machst und ich mich eben bei cloud und cms und so erstmal austobe bzw. das mein hoheitsgebiet ist. ändern können wir es hinterher immer noch - aber so frustriert mich das nur extrem. vertrau mir da einfach und lass dir gesagt sein, dass ich mich da an erfolgreichen webprojekten wie dem doodle, dem pad und ähnlichen orientiere. 

beispielsweise schreibst du: 
> cms brauchen wir hauptsächlich für die Verwaltung mehrerer Files. Eigentlich könnten die User das selbst lokal in ihrer persönlichen Ordnerstruktur vorhalten und zum anonymen Bearbeiten jeweils neu importieren. Wir bieten quasi nur die bequeme Option, alle slidenotes auf einen Blick online verwaltet zu sehen.

und das ist so falsch, dass ich garnicht weiß, wo ich anfangen soll. nur mal stichwort-mäßig: wir bauen eine webapp und keine desktop-app. das cms ist für das vorhalten der slidenotes wichtig weil es der primäre speicherort der slidenotes ist. nur angemeldete nutzer können in der cloud speichern. anonyme nutzer können nur einen eingeschränkten slidenote-editor benutzen. die lokale ordnerstruktur ist für desktop-apps wichtig, aber nicht für web-apps. die präsentationen werden ebenfalls vom cms gehostet, damit der user nur noch invitation-links rumschicken muss und es die zentrale stelle gibt, an der kommentiert werden kann (besser als bei einer pdf). die präsentationen in der cloud sind selbstverständlich ebenfalls verschlüsselt. kommentiert werden können nur präsentationen, nicht slidenotes - slidenotes sind rein privat. die kommentare der präsentationen können gesammelt und getrennt angezeigt werden, sowohl alleinstehend als auch am rande der präsentation.
und natürlich: wir wollen, dass die user sich anmelden (kostenpflichtig). da bietet es sich an, das cms fucking good zu machen, so dass die user garnicht mehr präsentationen per e-mail-anhang rumschicken wollen sondern per link - und so die user zu uns quasi gestoßen werden. 
ziel sollte sein, dass user an slidenotes.io gebunden werden, weil sie das so geil finden wie doodle oder ähnliches.

ich hoffe du siehst, dass ich da einfach schon verdammt viel hirnschmalz reingesteckt habe. gibt genügend andere baustellen, die unsere aufmerksamkeit brauchen. daher würde ich das gerne an mich nehmen und einfach machen.

**Comment by jochmann** [comment]
> das cms ist für das vorhalten der slidenotes wichtig weil es der primäre speicherort der slidenotes ist. nur angemeldete nutzer können in der cloud speichern
> 
- alle Nutzer können trivialerweise geschriebenen Text lokal in ihrem eigenen Dateisystem speichern. Vielleicht schreiben sie auch lieber in Textedit oder Atom und kopieren dann den Text in den slidenots editor. der einzige "proprietäre" Text, den slidenotes produziert sind die base64-Bilder und der Verweis darauf.
- nur angemeldete Nutzer können in der Cloud speichern

> anonyme nutzer können nur einen eingeschränkten slidenote-editor benutzen.
> 
- der editor ist identisch, manche exportfunktionen (publizieren) und das speichern in der cloud (und damit die Arbeit an mehreren Dokumenten gleichzeitig) sind angemeldeten usern vorbehalten.

> die präsentationen werden ebenfalls vom cms gehostet, damit der user nur noch invitation-links rumschicken muss und es die zentrale stelle gibt, an der kommentiert werden kann (besser als bei einer pdf)
> 

- Die HTML-Präsentationen können "publiziert" werden und werden dann von uns gehostet. Das ist quasi ein Export in die Cloud. Sollte ich aber im UI noch mal eigens anlegen. Statt des "save" buttons, der momentan in der Kopfzeile steht, vielleicht "publish"
- Kommentare sind nur als mögliche Entwicklungsrichtung überhaupt in der road map vorgesehen. Kommentare fügen eine sehr komplexe Dimension von Nutzer-Interaktion ein, wo wir später erst noch definieren müssen, wie wir soziale Interaktion auf unserer Plattform abbilden.  Zum Start wird es keine Kommentarfunktion geben.

**Comment by gaenseklein** [comment]
> alle Nutzer können trivialerweise geschriebenen Text lokal in ihrem eigenen Dateisystem speichern. Vielleicht schreiben sie auch lieber in Textedit oder Atom und kopieren dann den Text in den slidenots editor. der einzige "proprietäre" Text, den slidenotes produziert sind die base64-Bilder und der Verweis darauf.

das ist aber für unsere webapp völlig irrelevant. für uns ist der text erst relevant, wenn er in die slidenote-webapp eingefügt wird. und ab da ist das für die webapp der code. der kann nicht mehr lokal gespeichert werden sondern nur noch in der cloud. er kann nur noch lokal exportiert werden, was aber nicht das gleiche ist. stell dir einen texteditor vor, der keine "speichern" option mehr hat sondern nur noch ein "speichern unter". jedesmal wenn du was verändert hast und speichern willst musst du erneut die datei auswählen und dem überschreiben zustimmen. das ist unser exportieren. das speichern von dateien, die gerade bearbeitet werden ist für eine webapp nicht möglich. daher können dateien auch nicht wirklich geöffnet werden sondern nur importiert. 

> - Die HTML-Präsentationen können "publiziert" werden und werden dann von uns gehostet. Das ist quasi ein Export in die Cloud. Sollte ich aber im UI noch mal eigens anlegen. Statt des "save" buttons, der momentan in der Kopfzeile steht, vielleicht "publish"

genau. es wäre gut, zwischen export von slidenote und präsentation zu unterscheiden. wie wäre es mit 
"backup"  und "publish"? kann imho auch ins selbe export-menü gepackt werden. soviele optionen sinds dann ja auch nicht. 

> - Kommentare sind nur als mögliche Entwicklungsrichtung überhaupt in der road map vorgesehen. Kommentare fügen eine sehr komplexe Dimension von Nutzer-Interaktion ein, wo wir später erst noch definieren müssen, wie wir soziale Interaktion auf unserer Plattform abbilden. Zum Start wird es keine Kommentarfunktion geben.

für mich sind kommentare schon wichtig weil ich kunden wie jan (frauenhofer institut) unser programm schmackhaft machen will und das ist ein riesen vorteil gegenüber pdf's per mail rumschicken. mit kommentaren ist das übersichtlicher (weil du nicht verschiedene pdf's mit unterschiedlichen kommentaren von jedem empfänger zurück bekommst sondern zentral an einer präsentation die kommentare angehängt werden), einfacher (es kann pro präsentation und dort pro slide kommentiert werden - auch während der betrachtung der präsentation), sicherer (alles ist verschlüsselt) und schicker (kommentare können ein- und ausgeblendet werden, sortiert werden etc.). 
ob sie zum start oder später kommen ist diskutabel, aber kommen sollten sie. "make the cloud great again". das konzept ist dabei recht simpel: präsentationen werden vom registrierten user published und sind dann öffentlich, aber verschlüsselt unter pseudo-zufalls-url abrufbar. dort können die (unangemeldeten) empfänger der präsentation sie aufrufen und nach eingabe des korrekten passworts ist es entschlüsselt. anschließend können sie die präsentation sich anschauen und kommentieren, wobei ihr kommentar mit demselben passwort wie das der präsentation verschlüsselt wird. durch die verschlüsselung ist nicht nur die datensicherheit gegeben sondern auch spam-schutz vor robots - unverschlüsselte kommentare bzw. kommentare, die nicht mit dem richtigen schlüssel verschlüsselt wurden werden beim user einfach nicht mehr dargestellt. die pseudo-zufalls-url erschwert es den bots darüber hinaus, die präsentation überhaupt zu finden, was das spam-aufkommen deutlich verringern sollte. sprich: ohne captcha oder anmeldung seitens der empfänger oder sonstige user-unfreundliche sachen haben wir eine sichere form des publishing, welche zudem auch noch auf dem server selbst nur verschlüsselt abgelegt wird und damit sicher vor 0-day attacken ist. 
ach ja: zum publishing kann natürlich auch ein neues passwort benutzt werden, es muss nicht das selbe passwort benutzt werden wie bei der erstellung und bearbeitung der slidenote. die abhängigkeit zwischen präsentation und slidenote ist one-way: aus einer slidenote wird eine präsentation erstellt, die dann als fertiges produkt veröffentlicht und nicht mehr bearbeitet wird. die slidenote ist davon natürlich unbetroffen und kann weiter verändert und neu published werden als neues produkt. so kann aus einer slidenote auch mehrere präsentationen (bspw. versionen nach rückmeldung durch empfänger) erstellt werden. 

nochmal: ich hab mir da einige gedanken zu gemacht und es sind nicht alle gedanken bereits oben eingeflossen. vielleicht sollte ich dir auch mal so grafiken erstellen, dass ersichtlich wird, was ich mir da gedacht habe. oder wir telefonieren dazu mal.

**Comment by jochmann** [comment]
> > alle Nutzer können trivialerweise geschriebenen Text lokal in ihrem eigenen Dateisystem speichern. Vielleicht schreiben sie auch lieber in Textedit oder Atom und kopieren dann den Text in den slidenots editor. der einzige "proprietäre" Text, den slidenotes produziert sind die base64-Bilder und der Verweis darauf.
> 
> das ist aber für unsere webapp völlig irrelevant. für uns ist der text erst relevant, wenn er in die slidenote-webapp eingefügt wird. und ab da ist das für die webapp der code. der kann nicht mehr lokal gespeichert werden sondern nur noch in der cloud. er kann nur noch lokal exportiert werden, was aber nicht das gleiche ist. stell dir einen texteditor vor, der keine "speichern" option mehr hat sondern nur noch ein "speichern unter". jedesmal wenn du was verändert hast und speichern willst musst du erneut die datei auswählen und dem überschreiben zustimmen. das ist unser exportieren. das speichern von dateien, die gerade bearbeitet werden ist für eine webapp nicht möglich. daher können dateien auch nicht wirklich geöffnet werden sondern nur importiert.

absolut, so hatte ich das auch gedacht.

> 
> > * Die HTML-Präsentationen können "publiziert" werden und werden dann von uns gehostet. Das ist quasi ein Export in die Cloud. Sollte ich aber im UI noch mal eigens anlegen. Statt des "save" buttons, der momentan in der Kopfzeile steht, vielleicht "publish"
> 
> genau. es wäre gut, zwischen export von slidenote und präsentation zu unterscheiden. wie wäre es mit
> "backup" und "publish"? kann imho auch ins selbe export-menü gepackt werden. soviele optionen sinds dann ja auch nicht.
> 

können wir gut erst mal so machen, ja.

> > * Kommentare sind nur als mögliche Entwicklungsrichtung überhaupt in der road map vorgesehen. Kommentare fügen eine sehr komplexe Dimension von Nutzer-Interaktion ein, wo wir später erst noch definieren müssen, wie wir soziale Interaktion auf unserer Plattform abbilden. Zum Start wird es keine Kommentarfunktion geben.
> 
> für mich sind kommentare schon wichtig weil ich kunden wie jan (frauenhofer institut) unser programm schmackhaft machen will und das ist ein riesen vorteil gegenüber pdf's per mail rumschicken. mit kommentaren ist das übersichtlicher (weil du nicht verschiedene pdf's mit unterschiedlichen kommentaren von jedem empfänger zurück bekommst sondern zentral an einer präsentation die kommentare angehängt werden), einfacher (es kann pro präsentation und dort pro slide kommentiert werden - auch während der betrachtung der präsentation), sicherer (alles ist verschlüsselt) und schicker (kommentare können ein- und ausgeblendet werden, sortiert werden etc.).
> ob sie zum start oder später kommen ist diskutabel, aber kommen sollten sie. "make the cloud great again". das konzept ist dabei recht simpel: präsentationen werden vom registrierten user published und sind dann öffentlich, aber verschlüsselt unter pseudo-zufalls-url abrufbar. dort können die (unangemeldeten) empfänger der präsentation sie aufrufen und nach eingabe des korrekten passworts ist es entschlüsselt. anschließend können sie die präsentation sich anschauen und kommentieren, wobei ihr kommentar mit demselben passwort wie das der präsentation verschlüsselt wird. durch die verschlüsselung ist nicht nur die datensicherheit gegeben sondern auch spam-schutz vor robots - unverschlüsselte kommentare bzw. kommentare, die nicht mit dem richtigen schlüssel verschlüsselt wurden werden beim user einfach nicht mehr dargestellt. die pseudo-zufalls-url erschwert es den bots darüber hinaus, die präsentation überhaupt zu finden, was das spam-aufkommen deutlich verringern sollte. sprich: ohne captcha oder anmeldung seitens der empfänger oder sonstige user-unfreundliche sachen haben wir eine sichere form des publishing, welche zudem auch noch auf dem server selbst nur verschlüsselt abgelegt wird und damit sicher vor 0-day attacken ist.
> ach ja: zum publishing kann natürlich auch ein neues passwort benutzt werden, es muss nicht das selbe passwort benutzt werden wie bei der erstellung und bearbeitung der slidenote. die abhängigkeit zwischen präsentation und slidenote ist one-way: aus einer slidenote wird eine präsentation erstellt, die dann als fertiges produkt veröffentlicht und nicht mehr bearbeitet wird. die slidenote ist davon natürlich unbetroffen und kann weiter verändert und neu published werden als neues produkt. so kann aus einer slidenote auch mehrere präsentationen (bspw. versionen nach rückmeldung durch empfänger) erstellt werden.
> 

ja, das ist ein total überzeugender use case und eine schöner Lösungsansatz. ich glaube aber, dass er für den Start dramatisch mehr Komplexität bringt. Die Basisfunktionalität sollte die Leute schon überzeugen. Den Sprung zum "sozialen Netzwerk" (denn das schaffst du an der Stelle!) können wir später noch machen.

> nochmal: ich hab mir da einige gedanken zu gemacht und es sind nicht alle gedanken bereits oben eingeflossen. vielleicht sollte ich dir auch mal so grafiken erstellen, dass ersichtlich wird, was ich mir da gedacht habe. oder wir telefonieren dazu mal.

gerne. ich will das auch nicht von der road map streichen, im Gegenteil. Ich halte das für die konsequente Weiterentwicklung des Cloud-Gedanken. Ich habe aber auch höchsten Respekt vor dem Mehraufwand jenseits von Programmieren, den das mit sich bringt. Konzeptionell ist das auf einmal kein "kleines Werkzeug zum Publizieren für 5€" sondern ein Netzwerk, wo die Nutzer schnell mit ganz viel Erwartungshaltungen reingehen, die du in der Gestaltung erst mal bedienen und steuern musst. Und dann hast du den Overhead von immerhin möglichem Spam und Missbrauch, um den wir uns auf einmal kümmern müssen. 

Plump gesagt: Darum will ich mich erst kümmern, wenn wir genug Geld mit der Basisfunktionalität verdienen, dass wir Leute für den Support anstellen können.

**Comment by gaenseklein** [comment]
bei einer reinen kommentarmöglichkeit von sozialem netzwerk zu reden ist doch ein wenig weit hergeholt. das ist standard im web, dass du sachen kommentieren kannst und auch per cms als default vorgegeben. 

zum mehraufwand: 
normalerweise würde ich dir recht geben - kommentare sind immer mit moderationsaufwand verbunden. aber bei uns nicht - denn: wir können diese kommentare nicht betreuen. das geht nicht, weil die liegen nur verschlüsselt in der datenbank und wir haben keinen einfluss auf sie bzw. können sie ja selbst nicht lesen. da bringen dir auch keine support-leute was. 
die sind auch nicht wirklich öffentlich sondern nur für die user/ersteller und empfänger der präsentation sichtbar. 

wo wir ein soziales netzwerk in zukunft brauchen (inklusive betreuungspersonal) ist bei dir mit der "community" ausgezeichnet. das ist aber eine andere baustelle als kommentare unter präsentationen.

**Comment by jochmann** [comment]
OK, wenn wir null Moderationsaufwand haben, können wir die reine Kommentarfunktion vielleicht tatsächlich recht früh integrieren. Kann da nicht einschätzen, wie du Backend mit Frontend verknüpfen willst und wie viel Aufwand das darstellt. Für die UI kann ich mir da was zu überlegen, hatte für pixelcraft ohnehin schon mal Überlegungen und Designs für zeilenbasierte Kommentare angestellt

**Comment by gaenseklein** [comment]
Die kommentare will ich nicht in den md-code einbauen, sondern über das cms regeln.
das macht auch logisch mehr sinn - die kommentare kommen ja zurück zum präsentierer und müssen nicht unbedingt erweiterungen an der stelle sein. darüber hinaus braucht es so für den empfänger der präse keine weitere syntax o.ä. zu lernen und wird nicht abgeschreckt durch md-code. funktioniert genau wie sonst kommentare auch - mit dem unterschied, dass die halt verschlüsselt werden.  
hab das auch eingebaut, kannst du dir ja mal anschauen.

**Comment by gaenseklein** [comment]
da keine rückmeldung kam und marie schon daran designt gehe ich davon aus, dass das so umgesetzt wird. issue closed
