### ISSUE TITLE
Export der Präsentation: reines html oder auch Javascript?

### ISSUE THREAD

**Issue by gaenseklein** [gaenseklein/slidenotes#49]
@jochmann 
Die Logik bisher ist, dass die Präsentation fertig erstellt wird und deren HTML abgespeichert wird. Von allen bisher getesteten Modulen machte nur das chartjs-Modul daraus ein Problem, da es mit dynamisch erstellten Canvas arbeitet, die erst zur Laufzeit erstellt und angepasst werden und eben nicht in html-Code umgewandelt werden. Das Problem für chartjs kann gelöst werden, indem die Canvas als Bilder abgespeichert und im HTML durch diese Bilder ersetzt werden. Dann sind sie aber nicht mehr dynamisch und es gehen viele schöne Sachen verloren (bspw. mit dem Mauszeiger an einen Punkt gehen um den Wert des Punktes zu sehen bei einer Line-Chart) und die Anpassung an die Größenverhältnisse des Bildschirms würde über CSS gelöst wie es auch sonst bei Bildern passiert. Das kann zu Verzerrungen und schlechter lesbarem Text innerhalb der Präsentation führen. 
Vielleicht kommen ja auch noch mehr neue Sachen hinzu, die auch in der Präsentation nur per Javascript funktionieren - bspw. der Code-Viewer den du mal per Telegram geschickt hattest. 
Daher würde ich mit Hilfe der chartjs die Möglichkeit einführen, dass Module auch Javascript in die Präsentation einfügen können.

**Comment by jochmann** [comment]
ich würde reines HTML klar bevorzugen. das hat auf mobilen Endgeräten fast Notwendigkeit, weil dort file://-urls <file:///-urls> aus Sicherheitsgründen der OS-architektur in einem speziellen Browser geöffnet werden, der kein JavaScript interpretiert, um die integriität des Dateisystems zu schützen.

Bei Chart.js würde ich dafür plädieren, dass wir nach einer Alternative suchen, die CSV in SVG umwandelt. Eventuell verschieben wir die Funktionalität auf eine spätere Version, wenn sich das als aufwändig darstellt oder wir das womöglich selbst programmieren müssen.

**Comment by gaenseklein** [comment]
> ich würde reines HTML klar bevorzugen. das hat auf mobilen Endgeräten fast Notwendigkeit, weil dort file://-urls <file:///-urls> aus Sicherheitsgründen der OS-architektur in einem speziellen Browser geöffnet werden, der kein JavaScript interpretiert, um die integriität des Dateisystems zu schützen.

Wow. Das ist ein deutlicher Rückschlag. Damit sind Präsentationen auf IOS nicht möglich, denn ohne Javascript ist es unmöglich, die Präsentation zu steuern. Es gibt hierfür aber zwei Fallbacks - zum einen ist unser Projekt eh auf "cloud first" ausgelegt. Für IOS würde das bedeuten "cloud only"...
Der zweite Fallback wäre, dass ich die Präsentationsslides untereinander darstellen lasse und per Javascript erst die entsprechende css-klasse anhänge, dass sie nacheinander klickbar dargestellt werden. Auf Maschinen, die kein javascript auf file:// zulassen wird die Präsentation dann im Fallback (statische html-seite) dargestellt während sie auf normalen Devices als Präsentation dargestellt wird. Dritte Möglichkeit: Vielleicht kann ich da sogar mit CSS-Pseudoklassen versuchen zu tricksen um eine Pseudopräsentation zu gewährleisten, aber versprechen will ich da nix und es wird maximal one-way laufen - sprich die Animation kann nur von vorne nach hinten durchgegangen werden und nicht zurückgeblättert oder gesprungen werden. Das wäre eine komplizierte Frickellösung, von der ich nicht sicher bin, ob sie überhaupt funktioniert aber die Idee könnte ich versuchen umzusetzen. 

Wovon sich aber auf IOS definitiv verabschiedet werden kann ist die Idee, eine verschlüsselte Präsentation als .html zu speichern, per e-mail zu verschicken und im IOS zu öffnen. Das ist definitiv nicht möglich ohne Javascript. 

> Bei Chart.js würde ich dafür plädieren, dass wir nach einer Alternative suchen, die CSV in SVG umwandelt. Eventuell verschieben wir die Funktionalität auf eine spätere Version, wenn sich das als aufwändig darstellt oder wir das womöglich selbst programmieren müssen.

Auch wenn die Lösung verlockend erscheint fänd ich es dann doch einfacher, die chart als .jpeg oder .png abzuspeichern und runterrechnen zu lassen - eventuell auch als Fallback wie oben gelöst - sprich für nicht-javascript-fähige Browser wird die jpeg genommen. Eventuell auch zwei jpegs abgespeichert (hochkant und breitkant) und über css wird das richtige Bild ausgewählt. Oder sogar noch mehr jpegs für verschiedene Bildschirmauflösungen... Klingt zwar kompliziert und bläht die Dateigröße der Präsentation auf, wäre aber relativ einfach umzusetzen im Gegensatz zu der Idee chart.js durch ein anderes Chart-Programm zu ersetzen. Viel schöner an der Javascript-Lösung für Chart.js sehe ich auch eher, dass die Zusatzfunktionen genutzt werden können (Mouse-Over Effekte, Animationen etc.). Das sieht einfach schöner aus als ein starres jpeg.

**Comment by jochmann** [comment]
alles halb so wild:

präsentationen (nur das abspielen, keine edit-funktionen mehr) gehen auf jeden fall über den "hashchange-event" in css. der triggert "display:block". funktioniert ja auch bei den pixelcraft html-büchern. jede slide hat ihren #anchor (id="001" etc). next-slide müsste dann über knöpfe (die ihrerseits den anchor verlinken) funktionieren, vielleicht bekommen wir es sogar mit dem swipe-event hin. link zu beispieldatei schicke ich noch.

das editieren erfolgt in der web-app, die wiederum eigene Spezifikationen und Privilegien auf iOS hat. das läuft ja auch nicht über file:/// <file:///> soweit ich weiß. export muss auf iOS ohnehin über E-Mail erfolgen, weil du eben keinen Zugriff aufs Dateisystem hast. Schauen wir mal.

zu SVG: das ist genau so interaktiv wie Canvas, und funktioniert dabei sogar ohne JavaScript. Mit css ::hover oder ::focus und ähnlichen tricks kannst du da animationen triggern. vor allem kannst du mit css SVG selbst responsiv machen, z.B. mit break points gewisse details ausblenden, wenn die grafik schrumpft. wirklich geiler scheiß, den ich irgendwann unbedingt bauen will (auch für pixelcraft-bücher und interaktive infografiken fürs marketing).

wir können vielleicht zunächst mit dem jpeg-fallback arbeiten, aber wenn das arbeit bedeutet oder unelegant aussieht, würde ich lieber zum start einfach ganz auf das feature verzichten und später nachrüsten.

**Comment by gaenseklein** [comment]
mit canvas2svg.js scheint es möglich zu sein, aus den chart.js canvas zu erstellen (ohne animationen etc.). Siehe https://stackoverflow.com/questions/45563420/exporting-chart-js-charts-to-svg-using-canvas2svg-js 

Was bleibt ist das Problem, dass wenn wir da ohne Javascript arbeiten müssen:
1. keine verschlüsselten Präsentationen mehr möglich sind. Das in Verbindung mit der Tatsache, dass Ipads saveAs() nicht unterstützen sondern die Präsentation auf jeden Fall an den Server gesendet werden muss, führt dazu, dass an unserem Server zumindest temporär unverschlüsselter Usercontent sprich Präsentationen gespeichert werden. 
2. die Präsentation deutlich unter ihren sonstigen Möglichkeiten bleiben wird, weil eben keine Javascript-generierte Effekte möglich sind 

Wohlgemerkt: wir reden hier immer nur von der exportierten .html-datei, die dann bspw. per e-mail verschickt wird. Die Cloud-Lösung, bei welcher nicht die Datei selbst sondern ein Link zu bspw. slidenotes.io/userxy/aShFlSk3D rumgeschickt wird hat all diese Probleme nicht.

**Comment by jochmann** [comment]
ja, bei der exportierten datei sehe ich auch kein Problem auf javascript zu verzichten, wenn von der web-app beim export alles als statisches html/css/svg gerendert wird. damit sind auch interaktive grafiken möglich. animationen, da siehst du nicht, ob mit javascript oder css getriggert.

von der exportierten html-datei aus gibt es doch gar nicht den fall, dass saveAs() relevant wird?? die soll ja nur zum abspielen der datei dienen.

ein export zu .txt (als backup für den späteren reimport) kann ja nur in der vollwertigen web app erfolgen. wo ist unser missverständnis?

**Comment by gaenseklein** [comment]
das missverständnis liegt glaube ich darin, dass wir zwei prozesse gleichzeitig diskutieren:
a) präsentation.html laden
b) präsentation.html speichern/exportieren

zu a) präsentation.html laden
die exportierte html-datei - die präsentation.html - soll verschlüsselt sein. das heißt es ist eine html-datei mit einem basis-layout, in welchem dann die `<div id="presentation">` ist. 
in diesem div ist verschlüsselter inhalt. dieser wird von einem javascript, welches in der präsentation.html enthalten ist, entschlüsselt (mit dem Passwort was beim Exportieren genutzt wurde) zu der erstellten präsentation aus dem export-prozess und die div anschließend mit dem entschlüsselten inhalt versehen. dann ist die präsentation fertig geladen und ab da kann sogesehen auch alles mit css passieren. 
ohne javascript kann ich den inhalt aber nicht entschlüsseln, das heißt ich kann die (verschlüsselte) präsentation.html nicht anzeigen. der fallback dafür ist, dass die präsentation.html unverschlüsselt exportiert wird, das heißt sie enthält den unverschlüsselten präsentations-html-code (inklusive grafiken etc. - eben den output nach dem parsen etc. so wie er jetzt dargestellt wird wenn du auf show Presentation klickst). dann kannst du dir das javascript dafür sparen, da es nicht entschlüsseln muss - also in der unverschlüsselten präsentation.html 

b) präsentation.html speichern/exportieren
um zu speichern erstellt das javascript zunächst den html-code der präsentation und verschlüsselt ihn dann. anschließend muss der verschlüsselte code in ein (passendes) template eingefügt werden und die so erstellte datei zum speichern dem user geliefert werden. das kann entweder per javascript direkt geschehen oder per php-code auf dem webserver. solange der content verschlüsselt ist ist das auch kein sicherheitsproblem. wenn wir aber unverschlüsselt abspeichern wollen fällt die option webserver aus, da zu diesem dann unverschlüsselter content käme, welchen er verarbeiten muss. das wollten wir ja vermeiden.

und aus dem zusammenspiel von a) und b) ergibt sich, dass du um einem ipad user eine präsentation zu schicken diese auf einem vernünftigen browser exportieren musst. also das ipad kann nur unverschlüsselte präsentations.html verwenden und diese können aber nicht mit einem ipad erstellt werden. 

ich frage mich nur, ob das für ipads wirklich relevant ist und sich da die mühe lohnt. ipad user sinds doch wie du schreibst selbst nicht gewohnt, dass sachen auf dem ipad selbst gespeichert werden. die sind doch mit der cloud viel besser bedient und da wir eh den ansatz cloud-first haben sehe ich da kein problem, eher im gegenteil. die sind doch froh, wenn da n link in der e-mail steht und dann sehen sie die präsentation eben im netz.
cloud-first hat ja auch weitere vorteile gegenüber einer statischen html-datei: es können beispielsweise kommentare/rückmeldungen von usern eingetragen werden. diese könnten dann sogar neben der präsentation auf wunsch angezeigt werden etc. das ist eine funktion, die ich glaube sehr stark genutzt werden könnte. (du kannst sogar pro slide kommentieren etc.) denn das ist der grund, warum bspw. im frauenhofer präsentationen als pdf verschickt werden - um darin kommentieren zu können und sie zurück zu schicken. eine in der cloud gehostete präsentation kann das von natur aus besser. (alle kommentare von allen usern sind in derselben präsentation, können aber auf wunsch separiert angezeigt werden etc.) 

abgesehen davon denke ich ist es für die monetäre verwendung besser, die leute an unsere cloud zu binden, also sie attraktiv zu machen :)

**Comment by jochmann** [comment]
ja, export ist halt eine unverschlüsselte datei.  finde ich auch OK, wenn wir das als Option anbieten

___
http://jochmann.me
exploring meaning in communication

**Comment by gaenseklein** [comment]
halt nur nicht fürs ipad. die sind raus und dürfen sich bei apple beschweren, dass saveAs nicht unterstützt wird.

**Comment by jochmann** [comment]
btw, ohne javascript einzelne slides anzeigen, siehe https://www.smashingmagazine.com/2015/12/reimagining-single-page-applications-progressive-enhancement/

**Comment by gaenseklein** [comment]
> btw, ohne javascript einzelne slides anzeigen, siehe https://www.smashingmagazine.com/2015/12/reimagining-single-page-applications-progressive-enhancement/

ja so etwas in der art meinte ich. man könnte jetzt noch für jede slide/page (im beispiel view genannt) ne eigene navigation schreiben mit vor und zurück links usw. das bläht zwar textmäßig auf, aber dann hast du es ohne javascript. oder gar die pages in links packen, so dass die gesamte page klickbar ist (dann darf aber kein link in der page selbst sein). es gibt bestimmt fallstricke bei all dem, aber mit css-gefrickel kann man da schon viel erreichen.

ich glaube aber nach wie vor nicht, dass uns das viel bringt. das einzig schöne an dem ansatz ist in meinen augen, dass der back-button eine funktionalität bekommt. ansonsten brauchst du eh javascript wenn du auf keystrokes reagieren willst etc. und es macht den code übersichtlicher in meinen augen wenn das in einem kleinen steuerobjekt gesammelt ist was der player an funktionalität bieten soll und eben nicht gestreut über html, css-tricks und javascriptcode. geschwindigkeitsmäßig/performance ist auch vernachlässigbar. außer die seite zu wechseln - sprich css-klassen neu anzuhängen - passiert da ja nicht viel. (auch wenn ich die idee aus dem artikel gut finde den screenreadern zu helfen aber das macht der ja auch per javascript.) 

und auch wenn ich mich wiederhole: wir brauchen eh javascript im normalen use-case wegen der verschlüsselung. wirklich sparen tun wir da nix - wäre vielleicht n netter fallback für unverschlüsselte präsentationen, aber sonst...

**Comment by jochmann** [comment]
der export ist natürlich unverschlüsselt - zumindest, wenn der export möglich ist, ohne dass unser server die unverschlüsselten daten sieht.

**Comment by gaenseklein** [comment]
vorschlag zur güte:
- es ist möglich, die präsentation unverschlüsselt lokal zu exportieren (mit saveAs() ) 
- die unverschlüsselte präsentation wird kein javascript enthalten um so kompatibel wie möglich zu sein
- die charts werden als hässliche pngs/canvas exportiert in unverschlüsselten präsentationen und die slidenote dafür aus kompatiblitätsgründen kastriert
- verschlüsselte präsentationen dürfen javascript enthalten und schönere charts und steuerungen etc. erstellen

**Comment by jochmann** [comment]
> On 7. Dec 2018, at 04:05, gaenseklein <notifications@github.com> wrote:
> 
> vorschlag zur güte:
> 
> es ist möglich, die präsentation unverschlüsselt lokal zu exportieren (mit saveAs() )
ja, unbedingt. es wird keine verschlüsselten Exporte geben. wir wollen Auswahlmöglichkeiten beschränken. Wer lokale backups verschlüsseln will, kann sich selbst um Verschlüsselung kümmern.
> die unverschlüsselte präsentation wird kein javascript enthalten um so kompatibel wie möglich zu sein
ja
> die charts werden als hässliche pngs/canvas exportiert in unverschlüsselten präsentationen und die slidenote dafür aus kompatiblitätsgründen kastriert
die charts werden immer als pngs von canvas exportiert, bis wir eine SVG-Lösung für die Charts finden. Oder wir verzichten auf charts, bis wir eine SVG-Lösung finden.
> verschlüsselte präsentationen dürfen javascript enthalten und schönere charts und steuerungen etc. erstellen
besser noch: es gibt nur eine export-variante des Präsentations-HTML. Lokal unverschlüsselt. wenn wir in der Cloud vorhalten sollen (dafür müssen wir noch im UI die Option gestalten) verschlüsselt. Beides mit dem gleichen Code-Inhalt: progressive enhancement. es wird JavaScript z.B. für Tastatursteuerung immer mit ausgeliefert, aber halt von manchen Browsern (mobil) ignoriert, so lange eine lokale Präsentation angezeigt wird. Online respektieren mobile browser dann die JavaScript-Vorgaben.

**Comment by gaenseklein** [comment]
> es wird keine verschlüsselten Exporte geben. wir wollen Auswahlmöglichkeiten beschränken.

finde ich einen klaren verstoß unseres "as a matter of principle all your data is encrypted...". da der export eh nur für slidenotes interessant ist würd ich dafür das proprietäre format ".slidenote" verwenden welches verschlüsselt ist. ist bereits implementiert und funktioniert super.

> die charts werden immer als pngs von canvas exportiert, bis wir eine SVG-Lösung für die Charts finden. Oder wir verzichten auf charts, bis wir eine SVG-Lösung finden.

ich denke, svg's als export sollte klappen mit dem plugin, siehe entsprechendes issue.

> es gibt nur eine export-variante des Präsentations-HTML. Lokal unverschlüsselt. wenn wir in der Cloud vorhalten sollen (dafür müssen wir noch im UI die Option gestalten) verschlüsselt

wenn du die präsentation unbedingt schlechter machen willst als nötig... ich verstehe den sinn nicht. export zu lokal sollte immer die sekundäre variante sein, primäre ist in die cloud (für angemeldete). wir wollen ja, dass die user die cloud benutzen weil sie geiler ist und dann dafür auch bereit sind geld zu zahlen.

**Comment by jochmann** [comment]
> > es wird keine verschlüsselten Exporte geben. wir wollen Auswahlmöglichkeiten beschränken.
> 
> finde ich einen klaren verstoß unseres "as a matter of principle all your data is encrypted...". da der export eh nur für slidenotes interessant ist würd ich dafür das proprietäre format ".slidenote" verwenden welches verschlüsselt ist. ist bereits implementiert und funktioniert super.

OK, überzeugt. .slidenote ist immer verschlüsselt. Beim Rest sollte ich vielleicht den Beschreibungstext anpassen - mir geht es nicht um Crypto, um des Crypto willen. Ich will klar machen und beruhigen, dass niemand die Daten lesen kann (auf dem Server liegt nur clientseitig verschlüsseltes Material) sofern du sie nicht explizit zum Lesen frei gibst. Auch wir nicht, und wir können sie auch nicht wieder herstellen. Wiederherstellung mit "send me a new password" ist halt leider erworbene Gewohnheit und da müssen wir gegensteuern. Ich hätte gerne, dass sie ihre "rohdaten" einfach immer selbst sichern.

> 
> > die charts werden immer als pngs von canvas exportiert, bis wir eine SVG-Lösung für die Charts finden. Oder wir verzichten auf charts, bis wir eine SVG-Lösung finden.
> 
> ich denke, svg's als export sollte klappen mit dem plugin, siehe entsprechendes issue.
> 

stark!

> > es gibt nur eine export-variante des Präsentations-HTML. Lokal unverschlüsselt. wenn wir in der Cloud vorhalten sollen (dafür müssen wir noch im UI die Option gestalten) verschlüsselt
> 
> wenn du die präsentation unbedingt schlechter machen willst als nötig... ich verstehe den sinn nicht. export zu lokal sollte immer die sekundäre variante sein, primäre ist in die cloud (für angemeldete). wir wollen ja, dass die user die cloud benutzen weil sie geiler ist und dann dafür auch bereit sind geld zu zahlen.

das stimmt - deswegen ja "progressive enhancement". Wenn wir es lösen können, dass alle Anzeige-Funktionalität ohne JavaScript gegeben ist, brauchen wir JavaScript nur für "Extras." Das heißt, dass niemand eine schlechtere Version bekommt, als die Rendering-Umgebung hergibt.

Export zu HTML bekommen nur angemeldete, zahlende user. Die sollen dann aber auch z.B. ihre HTML-Dateien per WhatsApp als Anhang verschicken können (JavaScript disabled). Unangemeldet geht nur "publish" (vielleicht mit einem Link, der nur 24h hält) oder ähnlich beschnittene Services.

**Comment by gaenseklein** [comment]
chartjs mit canvas2svg hat nicht auf anhieb geklappt. das ist auch ein blöder ansatz. habs jetzt ersetzt durch chartist.js . damit haben wir nur eine abhängigkeit und der svg-code ist viel sauberer. 
bzw. bin noch dabei, alles umzusetzen. der vorteil ist klar: es ist eine svg-lösung und es kann fast alles über css gelöst werden. auch animationen. aber auch chartist.js setzt javascript ein, wo css alleine nicht weiter kommt beim responsive. insbesondere beim skalieren des svg (anpassung von schriftgrößen, pinseldicken etc.) zumindest hab ich das so verstanden. ein progressive enhancement sollte aber möglich sein. 
mehr zu chartist.js im issue #72 und zu charts momentan allgemein: #73 #74

**Comment by jochmann** [comment]
alles klar, gut überlegt, danke!

**Comment by gaenseklein** [comment]
chartist kann von haus aus keine nachträgliche skalierung des svg durch den browser/css sondern nur durch javascript. ich habe es jetzt so hingekriegt, dass die svg eine feste viewBox bekommt, dadurch kann die svg wieder skaliert werden. die viewBox richtet sich nach der letzten ausgabe bei der erstellung der chart. da diese bildschirmgebunden ist, bestimmt also die erstellung die größe bzw. die relationen des svg. durch ein nachträgliches skalieren bleiben zwar die relationen erhalten, aber eben nur die und das kann unter umständen unerwünscht sein. bspw. auf kleinem bildschirm erstellt und später auf großem dargestellt wird der text zu groß und umgekehrt. 
zwei möglichkeiten: 
1. wir gucken erstmal, wie weit wir das mit css minimiert kriegen (unterschiedliche schriftgrößen etc. für die bildschirmgrößen)
2. wir verwenden die erstellte svg als fallback und wenn javascript vorhanden ist tauschen sie wir durch eine dynamische, von chartist.js neu erstellte svg aus.

was mehr arbeit macht kann ich grad nicht sagen.

**Comment by gaenseklein** [comment]
wenn wir das zoom-plugin verwenden wollen brauchen wir definitiv javascript in der präsentation. ich würds auch gerne anbieten, weil es gerade für präsentationen eine schöne und brauchbare funktion ist, in graphen hineinzoomen zu können.

**Comment by jochmann** [comment]
Lass das dann aber mal auf später verschieben. Erst mal sehen, ob wir eine funktionale Version ohne hinbekommen

**Comment by gaenseklein** [comment]
es ist jetzt alles möglich wie es sein sollte: 
es gehen unverschlüsselte html-exporte, die ohne javascript funktionieren. Alle anderen setzen Javascript vorraus, da ja entschlüsselt werden muss. Da eh Javascript aktiviert ist wird online die Präsentation "neu erstellt". Das hat Sicherheitsgründe: Da wir verschlüsselt hochladen lassen kann der User jeglichen malicious content hochladen und wir haben keine Möglichkeit einzugreifen. Das Opfer wird aber uns dafür verantwortlich machen. Daher habe ich das online anders gelöst: Der Code muss vom Javascript interpretiert werden, alleine kann er nichts machen. Das bietet schon einiges an Schutz vor bösartigen Scripts. 
Issue closed
