### ISSUE TITLE
back-button mit sicherheitsfrage (unsaved edits) verknüpfen

### ISSUE THREAD

**Issue by jochmann** [gaenseklein/slidenotes#50]
die Browser-History sollte erst nach Sicherung zur "zurück" funktion finden

**Comment by gaenseklein** [comment]
Welche Sicherung ist gemeint? 
a) lokal im localStorage
b) im CMS

a) ist ja quasi erledigt, da andauernd gesaved wird. Man müsste schon sehr schnell sein, um vor der Sicherung auf den Back-Button zu kommen. 
b) kann generell mit einer prüfung in window.onbeforeunload erledigt werden - sprich, wenn auf den Back-Button gedrückt wird wird überprüft, ob der aktuelle Stand auch im CMS ist. Wenn nicht gibt es ne Warnung und der User kann die Aktion (Back-Button) abbrechen.

**Comment by jochmann** [comment]
ok. ich dachte eher als UX-element, um dem User die Sicherheit zu geben, dass wir "aufpassen". aber kann sein, dass es wirklich nicht relevant ist.

**Comment by gaenseklein** [comment]
war aber n guter punkt - hab beim testen grad gemerkt, dass ich "parselater" rausgeschmissen hatte, sprich nach keystrokes, die kein neu-parsen auslösen passierte einfach nichts. das hab ich dadurch entdeckt, das darf ja nicht sein. ich implementier das grad wieder - heißt: wenn der user 500ms nicht interagiert hat nach dem letzten keystroke, der KEIN neu parsen ausgelöst hat dann wird neu geparsed - um auch diesen fall einzuholen. evtl. war das auch der grund für #40 
der zusammenhang ist, dass jedesmal wenn neu geparsed wird auch das saven im localStorage ausgelöst wird. Ein überprüfen im window.onbeforeunload ob die aktuelle version auch im localStorage gespeichert ist ist leider nicht möglich, da das hashen eine asynchrone funktion ist und somit vorher erledigt werden sein muss bevor window.onbeforeunload ausgelöst wird (der browser wartet in onbeforeunload nicht darauf, bis das hashen fertig ist). und wenn das eh vorher erledigt sein muss kann es genauso gut bereits im localstorage gesaved sein - das ist kein unterschied. aber da eh fast die ganze zeit im localStorage gesaved sein soll sollte es da auch keinen datenverlust geben. 

implementiert ist jetzt bereits die abfragemöglichkeit für das cms - das muss aber später anders gelöst werden wenn das drupal im hintergrund läuft. momentan ist nur geprüft, ob der text im absendeformular der richtige/gleiche wie der im localStorage ist. später muss natürlich geprüft werden, ob das auch im cms tatsächlich gesichert ist. da das aber nur mit laufendem webserver sinn macht verschiebe ich dieses detail auf später. (ist ne simple abfrage, die auf tokens der form-id überprüft)

**Comment by gaenseklein** [comment]
jetzt wird auch nach 500ms pause gespeichert. ich schließe daher das issue
