### ISSUE TITLE
dragndrop of files in textarea behandeln

### ISSUE THREAD

**Issue by gaenseklein** [gaenseklein/slidenotes#53]
dragndrop von dateien in textarea behandeln:

- [x] images (jpg, jpeg, png, gif ...)
- [x] text (txt, md)
- [x] encrypted slidenote (slidenote)
- [x] csv (csv)

**Comment by gaenseklein** [comment]
erste version fertig: 
images werden von imgtourl.js gehandelt, alle textfiles vom slidenoteguardian.
@jochmann: 
bei drop von images wird image-upload-screen aufgerufen mit gedroptem image in vorauswahl. dabei wird gecheckt ob der cursor innerhalb eines bild-tags stand `![](meinbild)` - ist das so, wird der tag benutzt. ansonsten wird ein neuer tag eingefügt mit dem dateinamen als bildnamen - also beim drop von example.jpg wird ein `![](example.jpg)` in den md-code eingefügt an der stelle des aktuellen cursors. 

bei drop von textdateien (txt, md, csv) sowie verschlüsselten slidenotes wird dialog aufgerufen mit vorschau des einzufügendem text sowie der frage ob bestehendes ersetzt werden soll oder an aktueller cursorstelle eingefügt werden soll. 

was schwierigkeiten macht ist die mausposition des drops zu benutzen anstelle des letztgültigen cursors. also das ich per maus aussuche, in welche zeile bzw an welche stelle ich das bild oder die textdatei einfügen will. hab ich auch noch nix zu gefunden, wie das gehen soll - nur andere, die das selbe problem haben aber keine lösung.

**Comment by gaenseklein** [comment]
csv würd ich noch erweitern wollen um abfrage, ob der cursor in einem data-block ist. falls nicht soll im einfügen/vorschauscreen eine auswahl erscheinen an möglichen datenblöcken - bspw. die drei chart-arten.

**Comment by jochmann** [comment]
finde ich ok, dass man erst den cursor positionieren muss. beim upload kann man über ein modal (eine überblendung, wo man das textfeld verdeckt) deutlich machen, dass es während des ziehens keine möglichkeit gibt, den cursor zu positionieren

**Comment by gaenseklein** [comment]
wenn ein csv file hochgeladen wird gibts im import-bildschirm zwei weitere buttons: insert as chart und insert as table. mehr datentypen sehe ich grad nicht für . (gibt es welche?) taucht nur auf, wenn cursor nicht innerhalb von einem datenobjekt ist (könnte noch genauer geprüft werden auf table und chart aber ich belasse es erstmal dabei).
des weiteren ist behoben, dass der import-button nur "einmal" bei gleicher datei funktioniert (reagiert auf onchange - aber wenn die selbe datei zweimal hintereinander ausgewählt wurde gibts keinen change und daher auch keine reaktion). die gleiche datei kann jetzt mehrfach hintereinander hochgeladen werden. ist insbesondere wichtig, wenn der user erst canceld und dann woanders einfügen will bspw. 
das issue ist damit abgearbeitet.
