### ISSUE TITLE
pfad für unangemeldete user

### ISSUE THREAD

**Issue by gaenseklein** [gaenseklein/slidenotes#58]
in der pdf ist vorgeschlagen, dass der pfad für unangemeldete user immer anonymous/titel_der_slidenote_programmierte nummer ist.

**Comment by gaenseklein** [comment]
@jochmann
hier liegt ein denkfehler vor: daten von unangemeldeten usern werden nicht in der cloud gespeichert und brauchen somit auch keine eigene url - die macht nur sinn für daten, die auf dem server liegen. unangemeldete user legen aber keine daten auf dem server ab sondern nur in ihrem localStorage. 
daher kriegen alle unangemeldeten user auch immer den selben pfad - bspw. slidenotes.io/tryit

**Comment by jochmann** [comment]
guter Punkt. Ich hatte überlegt, wie man beim "onboarding" user an die Anmeldung heranführt und schon die Funktionen andeutet, die angemeldete user haben. muss ich noch mal überlegen. ist aber grundsätzlich gut, hier einen klaren anreiz zum anmelden zu haben

**Comment by gaenseklein** [comment]
du kannst natürlich auch einfach eine url "faken", sprich: anstelle von slidenotes.io/tryit nimmst du slidenotes.io/anonymous/slidenotetitle und intern verweist das immer auf das selbe. (das ist wichtig auch fürs caching von unangemeldeten usern, die sollen so wenig traffic wie möglich verursachen bei uns) 
dann brauchst du dich aber auch nicht um nummern zu kümmern, das ist ja scheiß egal, was nach anonymous kommt, da es keine entsprechenden nodes in der datenbank gibt. wenn zwei user also denselben slidenote-title verwenden kommen die sich ja trotzdem nicht in die quere. 
aber imho macht das wenig sinn - wer guckt schon auf die url? 
wenn du die user an die anmeldung heranführen willst kannst du das besser über die anderen sachen machen, die du ja bereits beschrieben hast (homebutton, cloud-zeichen, "publish presentation" ausgegraut oder auch verweisend auf registrierung etc. - eine herangehensweise die ich dazu gelernt habe ist: möglichst alle funktionen für angemeldete user sollten für unangemeldete sichtbar sein, aber immer zur registrierung führen)

**Comment by jochmann** [comment]
gut erklärt. ja, machen wir mit deiner /tryit-Idee.

wollte genau das Prinzip auch haben, dass die unangemeldeten user auf Elemente klicken, die dann mit einem Erklärtext auf die Registrierung verweisen.
