### ISSUE TITLE
keyboard commands

### ISSUE THREAD

**Issue by jochmann** [gaenseklein/slidenotes#6]
- cmd/strg-z -> undo
- ESC -> exit (enter?) presentation mode
- left-arrow, right-arrow -> advance slide in presentation mode
- number + ? -> jump to slide in presentation mode

**Comment by gaenseklein** [comment]
cmd/strg-z -> undo: ist n browser/editor-kommando. wirklich wegnehmen und selbst machen?
alle anderen kommandos sind für die präsentation. sollte deutlich unterschieden werden, was für präsentation gilt und was für slide.

**Comment by gaenseklein** [comment]
@jochmann cmd/strg-z -> undo: fasse ich nicht an wg. guideline keine browsertypischen befehle zu übersteuern. das muss der jeweilige browser selbst erledigen (tut firefox und chrome auch wie es soll)
präsentation hat jetzt ne steuerung über keyboard bekommen: 
Arrow-Left: Gehe eine Seite zurück
Arrow-Right: Gehe eine Seite vor
Space: Gehe eine Seite vor
Escape: Schließe Präsentation
Nummer + Enter: Gehe zu Seite Nummer (1 dann Enter = Seite 1; 1 dann 2 dann Enter = Seite 12, Seiten fangen bei 1 an, nicht bei 0 wegen Natürlichkeit der Eingabe)
