### ISSUE TITLE
context-feld mit "select a markup" (default) ändert sich, wenn es eine selection gibt

### ISSUE THREAD

**Issue by gaenseklein** [gaenseklein/slidenotes#63]
das context-feld bekommt einen default, welcher immer angezeigt wird wenn nix anderes da ist. 
der default ändert sich, je nachdem ob es eine selection im text gibt (text ausgewählt ist) oder ob nur ein cursor da ist. 
wenn der cursor innerhalb eines aktiven objekts ist (bspw. image, chart) oder diesen in einer selection beinhaltet soll sich das context-feld dementsprechend anpassen und nicht mehr den default sondern den zum jeweils aktiven objekt gehörigen kontext anzeigen. 
kontext-feld erstellen für
images
charts 
code 
latex
...

**Comment by gaenseklein** [comment]
@jochmann 
im pdf ist das context-feld auf der linken seite, über der sidebar und verdeckt aber nicht links die buttons. 
soweit klar. 
dann aber ist es mal unter der aktuellen cursorline bzw. wenn das insert-feld auf ist auch unter diesem. beim bild-context hast du es dann aber auf einmal über die cursorline gepackt. 
hast du da eine logik drinne, die ich grad nicht sehe? oder war das bild ein versehen und sollte eigentlich auch unter die cursorline?

des weiteren ist mir dabei aufgefallen, dass das die sidebar ganz schön voll macht - von der eigentlichen sidebar ist dann irgendwann relativ wenig zu sehen. ich würd das aber erstmal fertig machen und dann sehen wir uns das an ob uns das wirklich gefällt?
mir fallen dann zwei optionen ein, wie wir damit umgehen:
1. wir packen weniger default-content in das context-feld (nicht immer anzeigen lassen sondern nur wenn auch was da ist - default wäre dann nichts anzeigen)
2. wir machen das insert-menü nur dann aufklappbar, wenn man an der stelle auch was inserten kann. bspw. wenn der cursor auf einem bild ist ist das kontext-feld sinnvoll (das bild darstellen etc.) - das insert-feld allerdings nicht - denn in ein image kannst du keine sections einfügen (bzw. solltest du nicht weil sonst das image nicht mehr funktioniert). das sind nicht viele fälle, aber in den fällen wäre es praktisch.

**Comment by jochmann** [comment]
die Logik, wann das Kontext-Feld über den Zeilenanzeiger rutscht ist: Standard ist unterhalb, wenn mehr Platz benötigt wird rutscht sie nach oberhalb. Begrenzung ist bündig mit Höhe des Textfeldes.

angezeigt werden soll das Kontext-Feld nur, wenn Text markiert ist oder das Menü ausgeklappt.

**Comment by gaenseklein** [comment]
ah ok, also ist das context-field eigentlich teil des insert-blocks - wird nur grafisch ein wenig anders dargestellt? 
fraglich ist nach wie vor der umgang bei aktivem objekt = bild-tag. hier machen die "insert"-funktionen keinen sinn weil sie den bild-tag zerstören würden. 
alternative zum anzeigen bei aufgeklapptem insert-menü wäre, wenn es nach einer zeit des stillstands angezeigt wird - bspw. user hat 5 sekunden keine eingabe gemacht oder ähnliches... 
ich setze das erstmal so um wie oben vorgeschlagen, also nur wenn insert-feld auf ist und wir gucken uns das mal an. (in der pdf war das nicht so)

**Comment by gaenseklein** [comment]
ich habs jetzt umgesetzt. schau es dir an wenn du zeit hast. glücklich bin ich nicht damit. ich denke, wenn du es so verwenden willst wie ich dich verstehe ist es ja jetzt an das insert-menü gebunden. wie oben bereits beschrieben macht das insert-menü bei bestimmten selections keinen sinn - bspw. bei einem image, aber auch bei allen sections, welche keinen md-code erlauben (also chart, table und latex zur zeit). 
bisher war das context-field nur als "hilfe" gedacht, d.h. es werden die entsprechenden hilfe-texte angezeigt. bei sachen wie image war bereits auswahl und vorschau von aktuellem bild zu sehen. da gab es auch noch nicht das insert-menü, daher hat das da sinn gemacht.
jetzt gibt es aber ein insert-menü und das hat optionen, mit welchen gearbeitet werden kann, welche aber wie oben beschrieben bei sections, welche keinen md-text erlauben sowie bei bild-tags keinen sinn ergeben. 
daher wäre es doch ganz gut, das zu berücksichtigen und irgendwie umzusetzen - bspw. dass das insert-menü sich ändert, wenn es auf einem bild-tag geöffnet wird und dort den bildupload bereitstellt - oder anderes beispiel wenn es auf einer chart ist, dass du dort per buttons den chart-typen auswählen kannst. (ist grad per context-field gelöst.) und das context-field ist ein reines hilfsfeld, welches tipps darstellt (wie bspw. den satz "select a markup..." 

sprich: das kontext-feld und das insert-menü neu denken, als gesamt-paket betrachten und komplett neu strukturieren. auch die buttons sollten dann, wo sie nicht verwendet werden können, entweder verschwinden oder (imho besser:) ausgegraut werden.

**Comment by gaenseklein** [comment]
hier mal eine idee, wie das insert-menü für chart aussehen könnte (das kontext-feld ist da noch wie momentan):
![chart-insertmenu](https://user-images.githubusercontent.com/31316726/50108662-1d070680-0236-11e9-8202-779db1bd1d42.png)

**Comment by jochmann** [comment]
die Logik werden wir uns ja auch wegen der Performanz noch mal ansehen müssen. Ich schau mal bei den anderen issues, was mir dazu einfällt.

**Comment by gaenseklein** [comment]
Wie in dem Beispiel zu sehen wäre es doch für die GUI am praktischsten und für den User am hilfreichsten wenn wir das insert-menü dynamisch anpassen können. Hilft bei der Erstellung der Chart doch sehr, wenn das so ausgewählt werden kann. Soll ich das mal umsetzen, dass Sections vom Default abweichen können?

**Comment by jochmann** [comment]
macht vermutlich Sinn, ja

**Comment by gaenseklein** [comment]
chartinsertmenu:
![chartinsertmenu](https://user-images.githubusercontent.com/31316726/54089118-d2dd7f00-4365-11e9-881b-34803a323243.png)
chartinsertmenu mit hover über auswahl von charts:
![chartinsertmenuhover](https://user-images.githubusercontent.com/31316726/54089134-0c15ef00-4366-11e9-8033-02d84a01a939.png)

**Comment by gaenseklein** [comment]
um das bei dir zu sehen musst du warscheinlich erst das neue chartist-plugin aktivieren (unter options -> advanced options -> extensions -> charts with chartist )

**Comment by jochmann** [comment]
cool!

**Comment by gaenseklein** [comment]
context-feld kommt weg, issue ist daher geschlossen. folgeissue: #78 neues context-menu (ehemals insertmenu)
