### ISSUE TITLE
optionsmenü

### ISSUE THREAD

**Issue by gaenseklein** [gaenseklein/slidenotes#65]
das optionsmenü soll drastisch verändert werden:

- [x] - es soll entschlackt werden
- [x] - es gibt keine voransicht des ausgewählten themes mehr (???)
- [x] - es wird neben der präsentation angezeigt, rechte sidebar
- [x] - presentation-design=css-theme auswahl (pop, tufte, console) ohne voransicht, aber mit theme-beschreibung, 
- [x] - darunter code-highlightning auswahl (?)
- [x] - darunter interface design: context-mode (standard), focusmode(ohne sidebar) 
- [x] - darunter night-mode-switch
- [x] - darunter links zu documentation, bug-reports, community 
- [x] - darunter copyright slidenotes.io

**Comment by gaenseklein** [comment]
@jochmann
1. du hast im optionsmenü ein auswahl-select für code-highlightning hinterlegt im pdf. 
ist damit das bisherige auswählen eines themes für code-highlightning gemeint? das fänd ich ungeschickt. ich hab das im alten menü (jetzt noch über advanced options erreichbar) gehabt, damit wir damit einfach rumspielen können und ausprobieren. wenn wir genügend evaluiert haben würde ich das ans theme koppeln (pop, tufte, console) - also je nachdem welches theme ausgewählt wurde wird dann auch das farbschema des code-highlightning übernommen. (z.B. für console nimm google-code, für tufte github etc.)
2. ich habe das advanced options menü hinzugefügt um das alte menü noch erreichbar zu haben. ob und wie das advanced menü später integriert wird ist mir an der stelle egal - wir brauchen es aber in der testphase denke ich noch öfters um sachen auszuprobieren. das kann dann später entweder komplett raus oder umgestaltet werden. aber für uns brauchen wir das noch und das passt da ja auch ganz gut hin.

**Comment by jochmann** [comment]
1. ich denke, welches code-highlighting Programmierer bei ihren Demos verwenden wollen, ist schon eine Wahl unserer User (weil damit konventionelle Bedeutung verknüpft ist). Geht ja nur um das Farbschema. Das muss halt in alle Themes passen, aber das sollte bei unseren sehr monochromen Designs ja kein Problem darstellen. Default bestimmen wir.
2. ok, das hatte ich ohnehin erwartet, dass wir ein "dev-menü" brauchen.

**Comment by gaenseklein** [comment]
1. ok, dann setze ich das so um. finde ich zwar nicht schlau, aber wenn du meinst...
