### ISSUE TITLE
passwort-eingabe-feld verändern

### ISSUE THREAD

**Issue by gaenseklein** [gaenseklein/slidenotes#66]
passwort-eingabe-feld mit re-type password und password-manager hilfe ausstatten, sowie den dazugehörigen text aus der pdf: 

as a matter of principle: everything you write is encrypted before we even store it on our server. please choose a password now. feel free to make one as simple or as complicated as you want. just
don't forget it: there is no password recovery!
 everything is encrypted right in your browser. always. you'll be prompted to choose a password as soon as you make edits to a document.
export an unencrypted copy as a text file (with images converted into code). you can also export a standalone presentation as an html file or a PDF.

we recommend using a password manager to keep up with the task of choosing and remembering safe passwords on the web.

**Comment by gaenseklein** [comment]
@jochmann
Ich habe die Logik jetzt ein wenig umgestellt um Passwort-Managern "zu helfen". Für den Passwort-Manager von Firefox funktioniert es jedenfalls. 
Damit ich mit dem Passwort-Manager gut klar komme und er einen Sinn ergibt habe ich das Re-Type-Password-Field optional gemacht. Heißt: solange da nichts eingetragen ist braucht es nicht verwendet werden. Ist einmal was in das Feld eingetragen muss der Inhalt gleich dem Passwortfeld-Inhalt sein. Ist das nicht der Fall (wird bereits während dem Tippen getestet und rückgemeldet) verfärbt sich das Feld rot. Ist das der Fall verfärbt es sich grün. 
Nicht-Vertragen heißt, dass Firefox sich leider nur das Passwort merkt und abspeichert für das Passwort-Feld. Das Re-Type-Feld wird nicht gespeichert und auch nicht ausgefüllt - was beim erneuten Laden den Passwort-Manager ein wenig überflüssig macht da ja das Passwort doch erneut eingegeben werden muss. 

Um dem Passwort-Manager zu helfen, die verschiedenen Notes auseinander zu halten habe ich ein e-mail-Feld gefaked. In dieses wird notetitel@slidenotes.io eingetragen. Dadurch kann der (firefox-)Passwortmanager die einzelnen Notes der Seite auseinander halten und sollte sie dementsprechend automatisch laden können. Idee ist, dieses Feld nachher per css zu verstecken (height:0px). Mal sehen ob das passiert.

Da können noch ein paar Fallstricke dabei sein, aber ich hoffe, dass wir so Passwortmanager gut unterstützt kriegen. 

Bitte Testen mit Browsern und Passwortmanagern deiner Wahl und gerne Rückmeldung geben was klappt und was nicht.

**Comment by gaenseklein** [comment]
ok, direkt erste änderung: anstelle von email-feld nehme ich username. dann kann ich auch leerzeichen etc. mit drinne haben und nicht nur valide e-mailadressen. 
zweite auffälligkeit: wenn das ~~username-feld~~ passwort-feld leer ist taucht im firefox bei klick auf das passwort-feld ein dropdown-menü auf mit allen notetiteln die je mit passwort gespeichert wurden. dann ists zwar nicht automatisch, aber easy auswählbar. das wäre ein guter fallback. 
denn ich kriege es momentan nicht hin, dass firefox was anderes als das "letzt-genutzte" dort einträgt. das kann aber auch später obsolet sein, je nachdem wie die passwort-manager das handeln, dass die url sich ändert. wenn sie die url mit als element nutzen um die richtige kombination username-passwort auszuwählen ist eh alles easy. jede slidenote hat ja eine eindeutige url. 
kann auch sein, dass es klappt, wenn der "username" (notetitel) bereits per html (php-ergebnis aus der jeweiligen url/datenbankabfrage) vorausgefüllt ist. das kann ich aber erst testen, wenn ein cms am start ist was das erledigt.

**Comment by gaenseklein** [comment]
des weiteren fiel mir noch ein: wäre es nicht gut, wenn das passwort auch gewechselt werden kann? also irgendwo ne option dafür hinterlegen, die das passwort resetet und nach nem neuen fragt, was ab dann für die speicherung benutzt wird?

**Comment by gaenseklein** [comment]
mit chromes passwort-manager klappts auch mit dem fallback. das re-type würd ich glaub ich dann auch verstecken wenn geladen/decrypted wird. das brauchts da ja nicht, sondern nur beim saven/eingeben eines neuen passwortes. oder was meinst du?

**Comment by gaenseklein** [comment]
noch ein einfall/idee nach weiterem arbeiten: wenn ich das feld bei der passwort-abfrage für den export sichtbar lasse kann ich dort die user den dateinamen eingeben lassen. dann kann der passwort-manager sogar lokale files verwalten sofern der user nicht gleiche dateinamen für verschiedene files benutzt :)

**Comment by jochmann** [comment]
nice

**Comment by gaenseklein** [comment]
denke, ich bin fertig damit. falls doch noch was kommt nochmal öffnen. ach ja, standard ist jetzt der fallback, d.h. das passwort-feld wird gelöscht und somit muss immer manuell ausgewählt werden. ein automatisches ausfüllen vom browser wird so leider nicht unterstützt - müssen wir im cms nochmal gucken, ob wir das da verbessern können bzw. wie da das zusammenspiel ist.
