### ISSUE TITLE
größe der chart bestimmen

### ISSUE THREAD

**Issue by gaenseklein** [gaenseklein/slidenotes#73]
wie groß soll die chart sein? keine triviale frage.

horizontal: maximum 100% des containers (seite oder section) ist okay. 

vertikal: 100% ist blöd, da so viel zu groß wird. 
hier kommt es im endeffekt drauf an, wieviel platz noch da ist. das ist aber nicht bekannt zum zeitpunkt der erstellung - oder doch? 

robuste erste lösung: wir legen das relativ von hand fest:
charts sind insgesamt ca 70% groß. 
eine chart auf der seite/in der section: 70%
zwei: 35%
drei: 25%

**Comment by gaenseklein** [comment]
das muss vom block-theme gelöst werden. es ist dessen aufgabe, heraus zu finden wie groß die chart sein darf. 
ansatz wäre zu sagen: eine line mit einer chart ist 1fr groß. alle anderen auto. so nimmt die chart immer den maximal möglichen raum ein und falls mehrere charts da sind teilen sie sich den maximal verfügbaren raum.

**Comment by gaenseklein** [comment]
klappt ganz gut der ansatz

**Comment by gaenseklein** [comment]
beißt sich aber mit der section:left auf gleicher seite aber chart außerhalb von section:left

**Comment by gaenseklein** [comment]
section:left/right auf gleicher seite führt zu 2fr oder mehr, dann passt es ganz gut. muss oder kann noch angepasst werden. bspw. auf 10fr siehts auch sehr gut aus. 10 fr hab ich mal gelassen. 
zur erklärung: 
bei sectionleft/right wird der grid-tabelle eine neue zeile nachgeschaltet, die die höhe 1fr hat und dadurch dafür sorgt, dass left/right sections bis zum ende der seite gehen. das ist insbesondere mit hintergründen wichtig. (hintergrundbild oder css-hintergrundfarbe vom theme)  - eine platzhalter-zeile.
dadurch teilen sich die zeilen mit der chart und eben dieser sectionleft-zeile den rest des verfügbaren platzes auf. da hier auch wieder gelten sollte, die chart so groß wie möglich zu machen, sollte ihre fraction ein vielfaches der platzhalterzeile bekommen. dadurch, dass die chart-zeilen aber die gleiche größe haben bleibt ihre relation erhalten.

**Comment by gaenseklein** [comment]
@jochmann: zusammenfassung von obigem: 
chart-größe bestimmt sich im grid. zeilen mit einer chart teilen sich den verfügbaren platz auf der seite unter sich auf (1fr), alle anderen zeilen bekommen größe "auto". 
sonderfall mit section-left/right auf gleicher seite: 
section hat eine platzhalterzeile (größe 1fr), daher müssen die chartgrößen in relation dazu gesetzt werden um sich nicht zu sehr den platz mit dieser platzhalterzeile zu verschwenden. daher bekommen sie die x-fache größe der platzhalterzeile (bspw. 10fr).

**Comment by gaenseklein** [comment]
Slide mit section-right mit hintergrundbild und chart und text ohne:
![bildschirmfoto-1](https://user-images.githubusercontent.com/31316726/53834009-3d6b7500-3f8a-11e9-84ea-3983ea71e4af.png)
zwei charts auf einer seite:
![2charts1page](https://user-images.githubusercontent.com/31316726/53834048-5aa04380-3f8a-11e9-9eb3-6c0cc9a1f3b9.png)
pie-chart in section-left, arealine außerhalb:
![grafik](https://user-images.githubusercontent.com/31316726/53834265-d8fce580-3f8a-11e9-8826-8428247dc9cf.png)

**Comment by gaenseklein** [comment]
section-right block mit hintergrundbild, chart im freien raum
![bildschirmfoto-1](https://user-images.githubusercontent.com/31316726/53834589-b7e8c480-3f8b-11e9-9c6f-92fe4b1316d3.png)
2 charts auf einer seite:
![2charts1page](https://user-images.githubusercontent.com/31316726/53834532-9091f780-3f8b-11e9-85cf-e8e328f6d2cc.png)
zwei charts auf einer seite, die pie chart in section-left:
![pie2area](https://user-images.githubusercontent.com/31316726/53834611-c7680d80-3f8b-11e9-8bba-cecbc69d1ad2.png)

**Comment by jochmann** [comment]
sehr geil
