### ISSUE TITLE
chart konfigurieren

### ISSUE THREAD

**Issue by gaenseklein** [gaenseklein/slidenotes#74]
die chart kann ja alle möglichen formen annehmen. frage ist, wie wir das auseinanderhalten bzw. konfigurieren lassen. 
dazu mal auf http://gionkunz.github.io/chartist-js/examples.html gucken, welche formen es gibt. 

mein ansatz wäre zu sagen, dass wir nur grobe richtungen anbieten und die konfiguration dahinter verstecken. die richtungen werden aufgerufen über ´´´chart:richtung
also bspw: ´´´chart:horizontalBar

In der Zukunft, wenn User das wünschen, könnte entweder über mehr variabeln im header oder eine erweiterung der syntax der user noch mehr vom standard abweichen wenn gewünscht. 

standard sind erstmal die drei:

- [x] line
- [x] bar
- [x] pie

dann fänd ich gut, wenn es noch gäbe:

- [x] areaLine
- [x] zoomLine
- [x] areaZoomLine
- [x] bipolarBar
- [x] stackedBar
- [x] horizontalBar
- [x] halfPie (gaugeChart)

alle sachen können kleingeschrieben werden, der camelcase dient hier nur der übersicht.

**Comment by gaenseklein** [comment]
für zoomLine und areaZoomLine braucht es javascript in der präsentation - fallback ist halt ohne zoom-funktion.

**Comment by gaenseklein** [comment]
alles jetzt soweit konfiguriert... @jochmann
hast du noch ergänzungen? sonst schließ ich das

**Comment by jochmann** [comment]
sauber. ich würde die JavaScript-erforderlichen Plugins erst mal ausklammern und in die Road Map auf später verschieben, dass wir sie wieder rein nehmen (zoom-line)
