### ISSUE TITLE
Bilder mit Base64-Encoden

### ISSUE THREAD

**Issue by gaenseklein** [gaenseklein/slidenotes#9]
Idee ist, dass Bilder anstelle als images als Base64-URI eingebunden werden. Der Vorteil ist, dass sie so direkt in einem Dokument sind und mit selbigem ausgespielt werden können - also dass fertige Slidenotes als eine HTML-Datei exportiert werden können - als auch dass sie leichter verschlüsselt abgespeichert werden können.

**Comment by gaenseklein** [comment]
Nebeneffekt der auftritt: Bilderverwaltung muss eingeführt werden. Also eine "Upload-Möglichkeit" für Bilder geschaffen als auch eine Speichermöglichkeit derselben eingeführt werden. Was wir auf keinen Fall wollen ist eine Base64-URL im MD-Code, denn das führt zu unleserlichen und unhandelbaren MD-Codes im Editor selbst. 
Lösungsidee wäre: Im MD-Code werden Bilder nach wie vor mit Namen angesprochen, also bspw. `![](meinbild.jpg)`
meinbild.jpg ist dabei der Name eines Bildes, welches per Upload in Base64-URI umgewandelt und angehängt wurde. Das Plugin sorgt dafür, dass dieses Bild dann an der Stelle bei der Ausgabe/Umwandlung in HTML per Base64-URI angehängt wird. 
Die Bilder werden in einem eigenen Array/Objekt gespeichert und verwaltet und an die Slidenote entweder unten dran gehängt mittels eines Image-Datenblocks (bspw. ||images||) oder aber extern in einem anderen Feld gespeichert.

**Comment by gaenseklein** [comment]
@jochmann Bildupload und interne Datenbank ist jetzt fertig. Was noch fehlt ist
1. eine wie auch immer geartete DragNDrop-Lösung
2. eine Form, wie diese Datenbank gespeichert wird - also entweder Intern im MD-Code oder in einem eigenen Textfeld außerhalb des MD-Codes. 

Zu 2., Speicherung des Bildes 
Innerhalb der Slidenote könnte bspw. ein Image-Code-Block eingeführt werden, also bspw. ||b64image||imagename
data:image/gif;base64,R0lGODlhDAAMAIABAAAAAP///yH5BAEAAAEALAAAAAAMAAwAAAIbjAOZZ8twIIutKeky3rYj/nkZYl3YhIbpcx0FADs=
||b64image|| 
Dieser Codeblock wird an die Präsentation unten dran gehängt und weder im WYSIWYG-Editor noch in der Präsentation angezeigt. Er wird dann vom Plugin benutzt um die Bilder in die interne Datenbank zu packen.
Vorteil ist, dass auch der MD-Code in einer Datei speicherbar ist. Fraglich ist allerdings der Nutzen, denn es hängt dann unten drann und nervt beim Arbeiten im MD-Code-Editor und gespeichert werden soll die Slidenote ja eh in einer Datenbank auf dem Server. 
Alternative wäre, diese Datenblöcke in ein anderes Textfeld zu packen. Vorteil wäre, dass dieses Textfeld für den Nutzer nicht einmal sichtbar sein muss - er sieht also nie die interne Struktur und wird von ihr nicht genervt. Es könnte dann mit dem gleichen Schlüssel wie die Slidenote verschlüsselt werden - macht also auch dahingehend keinen Mehraufwand und würde im CMS nur verschlüsselt abgespeichert werden. 

Ich präferiere zweite Lösung, also das speichern im externen Textfeld. Für die endgültige Präsentation, also die exportierte Slidenote, macht es auch keinen Unterschied, da hier der MD-Code garnicht mehr gebraucht wird und die Bilder eh per Data-URL im HTML-Text bereits enthalten sind. Es geht nur um die zu bearbeitende Slidenote. Der Vorteil von ersterem, dass alle Daten bereits im MD-Code enthalten sind, verschwindet ja bereits dadurch, dass wenn jemand seine Präsentation in einem anderen Editor schreibt und nachher nur noch in die Slidenote kopiert er dazu auch noch jedes Bild selbst händisch zunächst in Base64 codieren müsste - was wohl kaum einer macht. Statt dessen würde ich in einem externen Editor ebenso nur die Dateinamen verwenden und dann nachträglich im Slidenote-Editor die Bilder hochladen.

**Comment by gaenseklein** [comment]
Images können zur Zeit über drei Formen eingebracht werden:
```
![](url/des/bildes.jpg) - extern liegende Bilder können so eingefügt werden
![](data:image/gif;base64,R0lGODlhDAAMAIABAAAAAP///yH5BAEAAAEALAAAAAAMAAwAAAIbjAOZZ8twIIutKeky3rYj/nkZYl3YhIbpcx0FADs=) direkte Eingabe des Base64-Codes
![](dateiname.jpg) mit Hilfe des Slidenote-Editors eingefügtes Bild
```

**Comment by gaenseklein** [comment]
feature ist fertig. schönheitskorrekturen etc. kommen später wenn rücksprache da ist

**Comment by jochmann** [comment]
zweite Lösung sieht elegant aus. Danke
